Repository koreader/koreader, pull requests merged in 2018-09, with the labels that each got.

#4237 Allow closing full screen dialogs with swipe down
  frontend/ui/widget/bookstatuswidget.lua
  frontend/ui/widget/keyvaluepage.lua
  frontend/ui/widget/menu.lua
  plugins/coverbrowser.koplugin/covermenu.lua
  plugins/coverbrowser.koplugin/main.lua
  plugins/goodreads.koplugin/doublekeyvaluepage.lua
  plugins/statistics.koplugin/readerprogress.lua
Labels: UX

#4241 [Statistics] Add estimate end of read
  plugins/statistics.koplugin/main.lua
Labels: enhancement

#4240 Gesture manager (initial)
  frontend/apps/filemanager/filemanager.lua
  frontend/apps/reader/modules/readergesture.lua
  frontend/apps/reader/readerui.lua
  frontend/depgraph.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/elements/reader_menu_order.lua
  frontend/ui/widget/container/inputcontainer.lua
  frontend/ui/widget/menu.lua
  plugins/kobolight.koplugin/main.lua
  plugins/statistics.koplugin/main.lua
Labels: UX, enhancement

#4248 Add OPDS authentication
  frontend/ui/widget/opdsbrowser.lua
Labels: UX, enhancement
