Repository koreader/koreader, pull requests merged in 2018-04, with the labels that each got.

#3827 [feat, UX] SDL: add Gtk3 filechooser
  frontend/device/input.lua
  frontend/device/sdl/device.lua
  frontend/device/sdl/event_map_sdl2.lua
Labels: UX, enhancement

#3830 [PocketBook] Add Inkpad 3 (PB740) definition
  frontend/device/pocketbook/device.lua
Labels: PocketBook

#3836 FileManager menu: split Settings tab into 2 tabs
  frontend/apps/filemanager/filemanagermenu.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/widget/touchmenu.lua
Labels: UX

#3841 [fix, UX] frontlightwidget: More space for text and centering
  frontend/ui/widget/frontlightwidget.lua
Labels: UX

#3844 Fix Menusorter
  frontend/ui/menusorter.lua
Labels: bug

#3847 [fix] Cache: don't overwrite same CacheItem
  frontend/cache.lua
Labels: bug

#3865 [fix] AppImage: use $XDG_DOCUMENTS_DIR if available
  platform/appimage/AppRun
Labels: AppImage, bug

#3866 [fix] AppImage advanced settings location
  frontend/apps/filemanager/filemanagersetdefaults.lua
Labels: AppImage, bug

#3868 platform/appimage/AppRun: remove debug flag
  platform/appimage/AppRun
Labels: AppImage

#3884 [feat] SDL2: add window icon (new logo)
  Makefile
  frontend/device/sdl/device.lua
  platform/ubuntu-touch/koreader.png
  resources/koreader.png
Labels: enhancement

#3898 Fix the bug where "Press" key does not open config menu on Kindle 4 NT
  frontend/apps/reader/modules/readerconfig.lua
Labels: Kindle
