Repository koreader/koreader, pull requests merged in 2018-03, with the labels that each got.

#3709 [feat, Kobo] Add H2O2 natural light
  frontend/device/kobo/device.lua
  frontend/device/kobo/powerd.lua
  frontend/device/kobo/sysfs_light.lua
Labels: Kobo, enhancement

#3718 [UX] Add InfoMessage about OCR
  frontend/apps/reader/modules/readerhighlight.lua
  frontend/document/koptinterface.lua
Labels: UX

#3722 Fix some issues with movable dict window
  frontend/ui/widget/container/movablecontainer.lua
  frontend/ui/widget/dictquicklookup.lua
  frontend/ui/widget/htmlboxwidget.lua
  frontend/ui/widget/textboxwidget.lua
Labels: UX, bug

#3723 Add date to git-rev version
  Makefile
Labels: enhancement

#3770 UIManager: avoid painting widgets covered by a full screen widget
  frontend/apps/filemanager/filemanager.lua
  frontend/apps/filemanager/filemanagerhistory.lua
  frontend/apps/opdscatalog/opdscatalog.lua
  frontend/apps/reader/modules/readerbookmark.lua
  frontend/apps/reader/modules/readertoc.lua
  frontend/apps/reader/readerui.lua
  frontend/ui/screensaver.lua
  frontend/ui/uimanager.lua
  frontend/ui/widget/bookstatuswidget.lua
  frontend/ui/widget/imageviewer.lua
  frontend/ui/widget/keyvaluepage.lua
Labels: UX, enhancement

#3780 [UX] apps/reader/modules/readerfooter: also redraw progressbar on height change
  frontend/apps/reader/modules/readerfooter.lua
Labels: UX

#3787 Update README.md: more Mac info
  README.md
Labels: documentation

#3795 [fix] NetworkManager:isConnected() exit code check
  frontend/ui/network/manager.lua
Labels: bug

#3799 [fix] calibrecompanion.plugin
  plugins/calibrecompanion.koplugin/main.lua
Labels: bug

#3801 [fix] kodev update $VERSION for `run android`
  kodev
Labels: Android, bug

#3809 [fix] Kobo suspend when touching screen
  frontend/ui/uimanager.lua
Labels: Kobo, bug

#3815 Code cleanup : deprecate the 'Enter' event, replaced with 'Press'
  frontend/device/android/event_map.lua
  frontend/device/input.lua
  frontend/device/kindle/event_map_keyboard.lua
  frontend/device/sdl/event_map_sdl.lua
  frontend/device/sdl/event_map_sdl2.lua
  frontend/ui/widget/buttontable.lua
  frontend/ui/widget/menu.lua
  frontend/ui/widget/radiobuttontable.lua
  plugins/coverbrowser.koplugin/listmenu.lua
  plugins/coverbrowser.koplugin/mosaicmenu.lua
Labels: UX

#3817 Fix the cursor not being reset in Coverbrowser
  frontend/ui/widget/menu.lua
  plugins/coverbrowser.koplugin/covermenu.lua
Labels: UX, bug

#3821 [feat] Add ReaderBack
  frontend/apps/reader/modules/readerback.lua
  frontend/apps/reader/readerui.lua
  frontend/util.lua
  spec/unit/inputtext_spec.lua
Labels: enhancement
