Repository koreader/koreader, pull requests merged in 2019-07, with the labels that each got.

#5108 android: add support for 3rd party dictionary apps
  frontend/apps/reader/modules/readerdictionary.lua
  frontend/device/android/device.lua
  frontend/device/android/dictionaries.lua
  frontend/device/generic/device.lua
Labels: Android, enhancement

#5118 Pocketbook 622 preliminary support
  frontend/device/pocketbook/device.lua
Labels: PocketBook

#5125 Fix Kindle model detection in some corner-cases
  frontend/device/kindle/device.lua
  spec/unit/device_spec.lua
Labels: Kindle

#5129 File manager - adding option to view unsupported files
  frontend/apps/filemanager/filemanager.lua
  frontend/apps/filemanager/filemanagermenu.lua
  frontend/apps/reader/readerui.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/widget/filechooser.lua
Labels: UX, enhancement

#5131 Cloudstorage - Adding option to view unsupported files
  frontend/apps/cloudstorage/dropbox.lua
  frontend/apps/cloudstorage/dropboxapi.lua
  frontend/apps/cloudstorage/ftp.lua
  frontend/apps/cloudstorage/ftpapi.lua
  frontend/apps/cloudstorage/webdav.lua
  frontend/apps/cloudstorage/webdavapi.lua
Labels: UX, enhancement

#5135 Fix: Status bar hides text with minimal bottom margin
  frontend/apps/reader/modules/readerfooter.lua
  frontend/apps/reader/modules/readertypeset.lua
  spec/unit/readerfooter_spec.lua
  spec/unit/readerrolling_spec.lua
Labels: UX

#5138 Gesture intervals configurable
  frontend/apps/reader/modules/readergesture.lua
  frontend/device/gesturedetector.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/elements/reader_menu_order.lua
  frontend/ui/widget/spinwidget.lua
Labels: UX, enhancement

#5146 Set font size for menu items
  frontend/apps/filemanager/filemanagermenu.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/widget/menu.lua
Labels: UX

#5147 feat: customizable articles count per sync
  plugins/wallabag.koplugin/main.lua
Labels: Plugin

#5149 [sdl] Add support arrow key for next/prev page
  frontend/apps/reader/modules/readerpaging.lua
  frontend/apps/reader/modules/readerrolling.lua
  frontend/device/sdl/device.lua
Labels: AppImage, Desktop

#5148 feat(wallabag): archiving instead of deleting articles
  plugins/wallabag.koplugin/main.lua
Labels: Plugin
