Repository koreader/koreader, pull requests merged in 2019-09, with the labels that each got.

#5297 handle file:// protocol URI scheme
  reader.lua
Labels: enhancement

#5300 [minor] New memory icon for footer
  frontend/apps/reader/modules/readerfooter.lua
Labels: UX

#5301 [fix] GetText: guard against empty strings in translation
  frontend/gettext.lua
  spec/unit/gettext_spec.lua
Labels: bug

#5305 [fix, Kobo] Save frontlight state on shutdown after suspend
  frontend/device/kobo/powerd.lua
Labels: Kobo, bug

#5303 Add fine tune buttons to horizontal margins
  frontend/ui/data/creoptions.lua
  frontend/ui/widget/configdialog.lua
Labels: UX

#5295 [feat, plugin] Add AutoScroll
  frontend/apps/reader/modules/readerrolling.lua
  frontend/ui/elements/reader_menu_order.lua
  frontend/ui/uimanager.lua
  frontend/ui/widget/spinwidget.lua
  plugins/autoturn.koplugin/_meta.lua
  plugins/autoturn.koplugin/main.lua
Labels: Plugin, enhancement

#5304 [fix] Let UIManager handle suspend logic
  frontend/ui/uimanager.lua
Labels: bug

#5289 [fix] Prevent crash when no page boxes
  frontend/document/koptinterface.lua
Labels: bug

#5306 Allow setting a fine-tuned font size as default
  frontend/ui/widget/configdialog.lua
  frontend/ui/widget/toggleswitch.lua
Labels: UX

#5310 [Android] Don't ship Noto
  Makefile
  frontend/fontlist.lua
  frontend/ui/font.lua
Labels: Android

#5316 [Cervantes]: launch QBookApp from KOReader
  frontend/ui/elements/common_settings_menu_table.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/elements/reader_menu_order.lua
  platform/cervantes/koreader.sh
Labels: Cervantes, enhancement, firmware

#5321 You have failed this city!
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#5326 disable wifi before returning to QT, improved sysfs read
  frontend/device/cervantes/device.lua
  platform/cervantes/koreader.sh
Labels: Cervantes, bug, firmware

#5318 [UX] Allow keyboard layout selection
  frontend/ui/elements/common_settings_menu_table.lua
  frontend/ui/elements/menu_keyboard_layout.lua
  frontend/ui/elements/reader_menu_order.lua
  frontend/ui/language.lua
  frontend/ui/widget/virtualkeyboard.lua
Labels: UX

#5334 [fix] ReaderGesture: Use getCurrentNetwork().ssid
  frontend/apps/reader/modules/readergesture.lua
Labels: bug

#5338 [fix] Add keyboard layout to filemanager menu
  frontend/ui/elements/filemanager_menu_order.lua
Labels: bug

#5349 [fix, Android] Set executable bit
  platform/android/llapp_main.lua
Labels: Android, bug

#5350 [fix] ReadSettings Inverse reading order
  frontend/apps/reader/modules/readerpaging.lua
  frontend/apps/reader/modules/readerrolling.lua
Labels: bug

#5351 [fix] Filesearcher crash on empty file attributes
  frontend/apps/filemanager/filemanagerfilesearcher.lua
Labels: bug

#5344 [plugin/statistics] Synchronize Current book with footer
  plugins/statistics.koplugin/main.lua
Labels: Plugin

#5345 Disable show chapter markers when progress bar is hidden in footer
  frontend/apps/reader/modules/readerfooter.lua
Labels: UX

#5361 [fix, Kobo] Don't crash trying to sync frontlight with Nickel.
  frontend/device/kobo/nickel_conf.lua
  frontend/device/kobo/powerd.lua
  spec/unit/nickel_conf_spec.lua
Labels: Kobo, bug

#5353 Messages in numberpicker widget
  frontend/ui/widget/numberpickerwidget.lua
Labels: UX

#5375 Add fine tune in line spacing
  frontend/ui/data/creoptions.lua
  frontend/ui/widget/buttonprogresswidget.lua
  frontend/ui/widget/configdialog.lua
  frontend/ui/widget/spinwidget.lua
Labels: UX

#5384 Fix: don't create sidecar file when indexing pdf documents
  frontend/document/pdfdocument.lua
Labels: bug

#5369 [feat] Allow setting any document cover as screensaver
  frontend/ui/elements/screensaver_menu.lua
  frontend/ui/screensaver.lua
Labels: enhancement

#5382 Set screenshot output folder
  frontend/ui/elements/common_settings_menu_table.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/elements/reader_menu_order.lua
  frontend/ui/widget/screenshoter.lua
Labels: enhancement

#5391 [chore] Remove unnecessary indent on new line
  frontend/apps/cloudstorage/dropbox.lua
  frontend/apps/cloudstorage/ftp.lua
  frontend/apps/opdscatalog/opdscatalog.lua
  frontend/ui/screensaver.lua
Labels: chore

#5389 Sort footer elements
  frontend/apps/reader/modules/readerfooter.lua
  frontend/ui/size.lua
  frontend/ui/widget/button.lua
  frontend/ui/widget/sortwidget.lua
Labels: UX

#5396 Fix: footer offset when orientation is changes
  frontend/apps/reader/modules/readerfooter.lua
Labels: bug

#5398 [fix] added PocketBook InkPad 3 Pro to device.lua
  frontend/device/pocketbook/device.lua
Labels: PocketBook

#5400 Update el_keyboard.lua
  frontend/ui/data/keyboardlayouts/el_keyboard.lua
Labels: UX

#5403 Fix: Incorrect width of separator line
  frontend/apps/reader/modules/readerfooter.lua
Labels: bug

#5393 fix: Truncate text in spinwidget
  frontend/ui/widget/spinwidget.lua
Labels: UX

#5404 [feat, UX] Ignore hold corners
  frontend/apps/reader/modules/readergesture.lua
  frontend/ui/elements/common_settings_menu_table.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/elements/reader_menu_order.lua
Labels: UX, enhancement

#5405 Two lines footer
  frontend/apps/reader/modules/readerfooter.lua
Labels: UX

#5407 [Kobo/Cervantes] Prefer using the ioctl over sysfs when setting the FL.
  frontend/device/cervantes/powerd.lua
  frontend/device/kobo/powerd.lua
  frontend/device/sysfs_light.lua
Labels: Kobo

#5414 Add Hebrew keyboard
  frontend/ui/data/keyboardlayouts/he_keyboard.lua
  frontend/ui/data/keyboardlayouts/keypopup/he_popup.lua
  frontend/ui/language.lua
  frontend/ui/widget/virtualkeyboard.lua
Labels: UX, enhancement, i18n

#5416 Use the proper LED driver on the Libra
  frontend/device/kobo/device.lua
Labels: Kobo

#5413 Add fine tune in contrast
  frontend/ui/data/creoptions.lua
  frontend/ui/data/optionsutil.lua
  frontend/ui/widget/configdialog.lua
  frontend/ui/widget/numberpickerwidget.lua
  frontend/ui/widget/spinwidget.lua
Labels: UX, enhancement

#5421 [Kobo] Unbreak the FL ramp-up/down.
  frontend/device/kobo/powerd.lua
Labels: Kobo, bug, firmware

#5423 [UX] add inverse reading order to gesture manager
  frontend/apps/reader/modules/readergesture.lua
  frontend/apps/reader/modules/readerpaging.lua
  frontend/apps/reader/modules/readerrolling.lua
Labels: UX, bug, enhancement

#5427 Better align buttonprogress in configdialog
  frontend/ui/size.lua
  frontend/ui/widget/buttonprogresswidget.lua
Labels: UX

#5419 [fix] add save dialog to more exit paths (#5418)
  frontend/apps/filemanager/filemanagermenu.lua
  frontend/apps/filemanager/filemanagersetdefaults.lua
Labels: UX

#5373 [UX] Use ProgressWidget in frontlight
  frontend/apps/reader/skimtowidget.lua
  frontend/ui/widget/frontlightwidget.lua
Labels: UX

#5432 Add fine tune for zoom(dpi) and font size
  frontend/ui/data/creoptions.lua
  frontend/ui/data/optionsutil.lua
  frontend/ui/widget/configdialog.lua
  frontend/ui/widget/toggleswitch.lua
Labels: UX

#5380 [feat] Add haptic feedback
  frontend/apps/reader/modules/readerstatus.lua
  frontend/device/generic/device.lua
  frontend/device/sdl/device.lua
  frontend/ui/widget/virtualkeyboard.lua
Labels: enhancement

#5431 Joplin support
  plugins/evernote.koplugin/JoplinClient.lua
  plugins/evernote.koplugin/main.lua
Labels: Plugin

#5438 Fix: Crash toggleswitch when args are empty
  frontend/ui/widget/configdialog.lua
  frontend/ui/widget/toggleswitch.lua
Labels: bug

#5439 Fix: Footer overflow screen after resize emulator window
  frontend/apps/reader/modules/readerfooter.lua
Labels: Desktop, bug
