Repository koreader/koreader, pull requests merged in 2019-12, with the labels that each got.

#5662 [UX] ru keyboard ё popup and translation
  frontend/ui/data/keyboardlayouts/keypopup/ru_popup.lua
  frontend/ui/data/keyboardlayouts/ro_keyboard.lua
  frontend/ui/data/keyboardlayouts/ru_keyboard.lua
Labels: UX

#5674 Transifex pull on release build
  Makefile
Labels: bug, i18n

#5670 android: make system fonts toggable
  Makefile
  frontend/apps/reader/modules/readerfont.lua
  frontend/fontlist.lua
  frontend/ui/elements/font_settings.lua
  frontend/ui/font.lua
Labels: Android, enhancement

#5657 fix continuous scroll & footer overlap
  frontend/apps/reader/modules/readerpaging.lua
Labels: bug

#5677 fix, crash when exporting notes
  plugins/evernote.koplugin/clip.lua
Labels: bug

#5679 New widget DoubleSpinWidget based on HyphenationLimits
  frontend/apps/reader/modules/readerhyphenation.lua
  frontend/ui/widget/doublespinwidget.lua
Labels: UX

#5684 fix: Crash FM after delete file from end of document action
  frontend/apps/reader/modules/readerstatus.lua
Labels: bug

#5659 [UX] Simple symbol keyboard layer paging
  frontend/ui/data/keyboardlayouts/en_keyboard.lua
Labels: UX

#5689 TextBoxWidget: fix crash on hold after end of text
  frontend/ui/widget/textboxwidget.lua
Labels: bug

#5691 TextBoxWidget: fix crash when empty last line and alignment center/right
  frontend/ui/widget/textboxwidget.lua
Labels: bug

#5692 Fix Romanian plural forms
  frontend/gettext.lua
  frontend/ui/language.lua
Labels: i18n

#5701 crash.log for cervantes and android
  .github/ISSUE_TEMPLATE.md
Labels: Android

#5708 Footer - add option chapter markers width
  .ci/check.sh
  .luacheckrc
  defaults.lua
  frontend/apps/reader/modules/readerfooter.lua
  spec/unit/defaults_spec.lua
Labels: UX

#5709 [fix] Restore most Japanese keyboard layers
  frontend/ui/data/keyboardlayouts/ja_keyboard.lua
Labels: bug

#5713 Finish Weblate migration
  .ci/after_success.sh
  Makefile
  README.md
Labels: i18n

#5715 Unbreak the KUAL extension
  Makefile
  platform/kindle/extensions/koreader/bin/koreader-ext.sh
  platform/kindle/extensions/koreader/config.xml
  platform/kindle/extensions/koreader/menu.json
  platform/kindle/libkohelper.sh
Labels: Kindle, bug
