Repository koreader/koreader, pull requests merged in 2019-11, with the labels that each got.

#5554 ButtonTable: taller buttons for easier tap
  frontend/ui/size.lua
  frontend/ui/widget/button.lua
  frontend/ui/widget/buttontable.lua
Labels: UX

#5556 CoverBrowser: fix files_per_page setting type
  plugins/coverbrowser.koplugin/listmenu.lua
Labels: bug

#5527 Add book to favorites
  frontend/apps/filemanager/filemanager.lua
  frontend/apps/filemanager/filemanagercollection.lua
  frontend/apps/reader/readerui.lua
  frontend/readcollection.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/elements/reader_menu_order.lua
  frontend/ui/widget/sortwidget.lua
  plugins/coverbrowser.koplugin/bookinfomanager.lua
  plugins/coverbrowser.koplugin/covermenu.lua
  plugins/coverbrowser.koplugin/main.lua
Labels: UX, enhancement

#5564 android: touchscreen toggle
  frontend/device/input.lua
  frontend/ui/elements/common_settings_menu_table.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/elements/reader_menu_order.lua
Labels: Android, enhancement

#5574 Revert "Fix frozen confirmbox when keyboard shown"
  frontend/ui/uimanager.lua
Labels: bug

#5575 [fix, plugin] Don't show full widget together with isOnline()
  plugins/evernote.koplugin/main.lua
  plugins/kosync.koplugin/main.lua
Labels: Plugin, bug

#5572 Prevent crash on local calibre OPDS server
  frontend/ui/opdsparser.lua
  frontend/ui/widget/opdsbrowser.lua
Labels: bug

#5579 Enable rewind button in sort widget
  frontend/ui/widget/sortwidget.lua
Labels: bug

#5580 default setting option always enabled
  frontend/apps/reader/modules/readerdictionary.lua
  frontend/apps/reader/modules/readerhighlight.lua
  frontend/apps/reader/modules/readerpaging.lua
  frontend/apps/reader/modules/readerrolling.lua
  frontend/apps/reader/modules/readertypeset.lua
Labels: UX

#5581 loading bar thicker
  frontend/apps/reader/modules/readerrolling.lua
  frontend/ui/size.lua
Labels: UX

#5588 [feat] Support callback function in VirtualKeyPopup
  frontend/ui/widget/virtualkeyboard.lua
Labels: UX, enhancement

#5592 Gesture to open Favorites
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#5596 Add Mark as read to end of document action
  frontend/apps/reader/modules/readerstatus.lua
  frontend/ui/elements/common_settings_menu_table.lua
Labels: enhancement

#5603 [fix] Tailor plurals match
  frontend/gettext.lua
Labels: bug

#5607 [fix] Prevent double library loads
  kodev
Labels: bug

#5583 [feat, UX] Pick keyboard layout from keyboard
  frontend/ui/data/keyboardlayouts/el_keyboard.lua
  frontend/ui/data/keyboardlayouts/en_keyboard.lua
  frontend/ui/data/keyboardlayouts/he_keyboard.lua
  frontend/ui/data/keyboardlayouts/ja_keyboard.lua
  frontend/ui/data/keyboardlayouts/ko_KR_keyboard.lua
  frontend/ui/data/keyboardlayouts/pt_keyboard.lua
  frontend/ui/data/keyboardlayouts/yazhert.lua
  frontend/ui/elements/menu_keyboard_layout.lua
  frontend/ui/widget/inputtext.lua
  frontend/ui/widget/keyboardlayoutdialog.lua
  frontend/ui/widget/virtualkeyboard.lua
Labels: UX, enhancement

#5608 [doc] Add coreutils to Mac brew dependencies
  doc/Building.md
Labels: documentation

#5591 Synchronize local folder with dropbox
  frontend/apps/cloudstorage/cloudstorage.lua
  frontend/apps/cloudstorage/dropbox.lua
  frontend/apps/cloudstorage/dropboxapi.lua
  frontend/ui/cloudmgr.lua
Labels: enhancement

#5610 [chore] Extract Cyrillic/Russian keyboard
  frontend/ui/data/keyboardlayouts/el_keyboard.lua
  frontend/ui/data/keyboardlayouts/en_keyboard.lua
  frontend/ui/data/keyboardlayouts/es_keyboard.lua
  frontend/ui/data/keyboardlayouts/fr_keyboard.lua
  frontend/ui/data/keyboardlayouts/ja_keyboard.lua
  frontend/ui/data/keyboardlayouts/ko_KR_keyboard.lua
  frontend/ui/data/keyboardlayouts/ru_keyboard.lua
  frontend/ui/data/keyboardlayouts/yazhert.lua
  frontend/ui/widget/virtualkeyboard.lua
Labels: UX, chore

#5613 Cloud storage UX improvements
  frontend/apps/cloudstorage/cloudstorage.lua
  frontend/apps/cloudstorage/dropbox.lua
  frontend/apps/cloudstorage/ftp.lua
  frontend/apps/cloudstorage/webdav.lua
Labels: UX

#5616 [fix] Prevent xtext crash by not freeing TextWidget prematurely
  frontend/ui/widget/radiobutton.lua
Labels: bug

#5606 [fix] Empty directory path and crash on TextWidget
  frontend/apps/filemanager/filemanagerutil.lua
  frontend/apps/reader/skimtowidget.lua
  frontend/ui/widget/bookstatuswidget.lua
  plugins/statistics.koplugin/readerprogress.lua
Labels: bug

#5620 [fix] PDF footer margins
  frontend/apps/reader/modules/readerpaging.lua
  frontend/apps/reader/modules/readerview.lua
  spec/unit/readerlink_spec.lua
Labels: bug

#5626 Fix and improvements of battery stats plugin
  plugins/batterystat.koplugin/main.lua
  spec/unit/batterystat_spec.lua
Labels: Plugin, bug

#5651 Translate file size unit
  frontend/util.lua
Labels: i18n

#5652 Add Moldavian diacritics to ru_keyboard
  frontend/ui/data/keyboardlayouts/keypopup/ru_popup.lua
  frontend/ui/data/keyboardlayouts/ru_keyboard.lua
Labels: UX
