Repository koreader/koreader, pull requests merged in 2019-02, with the labels that each got.

#4517 add basic support for android eink refreshes on some rockchip devices
  frontend/device/android/device.lua
  frontend/device/generic/device.lua
  frontend/device/sdl/device.lua
  frontend/ui/elements/screen_eink_opt_menu_table.lua
Labels: Android, enhancement

#4537 [fix, lang] More accurate auto-DPI text
  frontend/ui/elements/screen_dpi_menu_table.lua
Labels: UX, bug

#4538 Page overlap menu (cre): set nb of overlap lines
  frontend/apps/reader/modules/readerhighlight.lua
  frontend/apps/reader/modules/readerpaging.lua
  frontend/apps/reader/modules/readerrolling.lua
  frontend/apps/reader/modules/readerview.lua
Labels: UX

#4557 [fix, Android] hasEinkScreen should be a function
  frontend/device/android/device.lua
Labels: Android, bug

#4558 [fix, Android] hasEinkScreen function in eink_opt_menu_table
  frontend/ui/elements/screen_eink_opt_menu_table.lua
Labels: Android, bug

#4562 [build, Android] Use faster lzma2 compression
  Makefile
Labels: Android

#4561 A few minor fixes after #4541
  frontend/apps/reader/modules/readerview.lua
  frontend/device/kobo/device.lua
  frontend/ui/widget/screensaverwidget.lua
Labels: bug

#4564 Some Wi-Fi tweaks
  frontend/device/generic/device.lua
  frontend/ui/network/manager.lua
  spec/unit/network_manager_spec.lua
Labels: enhancement

#4569 [Android] kodev run android: show all errors
  kodev
Labels: Android

#4568 [fix, AppImage] writable zsync outbox location
  plugins/zsync.koplugin/main.lua
Labels: AppImage, Plugin, bug

#4600 [UX] ReaderGesture: add back to previous location as an option
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#4601 [UX] ReaderGesture: More gestures (suspend, history, rotation)
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#4606 [feat] GestureDetector: add multiswipes
  frontend/device/gesturedetector.lua
Labels: UX, enhancement

#4607 [feat] Gesture manager multiswipes
  frontend/apps/reader/modules/readergesture.lua
Labels: UX, enhancement

#4612 [fix] GestureDetector typo
  frontend/device/gesturedetector.lua
Labels: bug

#4613 [fix] GestureDetector: multiswipe rotation
  frontend/device/gesturedetector.lua
Labels: bug

#4623 [fix] Gesture manager: check multiswipe defaults
  frontend/apps/reader/modules/readergesture.lua
Labels: bug

#4610 [UX] Gesture manager: add paged zoom gestures
  frontend/apps/reader/modules/readergesture.lua
  frontend/apps/reader/modules/readerzooming.lua
Labels: UX

#4620 [feat] Update check
  frontend/device/android/device.lua
  frontend/device/sdl/device.lua
  frontend/ui/otamanager.lua
Labels: AppImage, enhancement

#4629 Leave size_t alone in FFI stuff
  frontend/ui/message/streammessagequeue.lua
Labels: bug

#4608 [fix] ReaderZooming: work around tiles that are too large
  frontend/apps/reader/modules/readerzooming.lua
Labels: bug

#4640 [fix] GestureDetector: fix multiswipe direction detection code
  frontend/device/gesturedetector.lua
Labels: bug

#4641 [feat, UX] Gesture manager: add option - open previous document
  frontend/apps/filemanager/filemanagermenu.lua
  frontend/apps/reader/modules/readergesture.lua
  frontend/apps/reader/modules/readermenu.lua
  frontend/apps/reader/readerui.lua
Labels: UX, enhancement

#4643 [fix] Gesture manager: actually register multiswipe
  frontend/apps/reader/modules/readergesture.lua
Labels: bug

#4644 [feat, UX] Add multiswipe recorder
  frontend/apps/reader/modules/readergesture.lua
Labels: UX, enhancement

#4645 [fix] ReaderGesture: don't crash without custom gestures
  frontend/apps/reader/modules/readergesture.lua
Labels: bug

#4639 [wip]: android: (re)enable downloads using full apks
  frontend/device/android/device.lua
  frontend/ui/otamanager.lua
Labels: Android

#4649 [fix, UX] GestureDetector: fix multiswipe length detection
  frontend/device/gesturedetector.lua
Labels: UX, bug

#4652 [UX] Gesture manager: delete custom gestures and update menu
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#4654 Gesture manager: re-order actions, add Skim option
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#4655 [UX] Gesture manager: show selected action in menu
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#4656 [fix] Gesture manager: default at the top
  frontend/apps/reader/modules/readergesture.lua
Labels: bug

#4658 [fix] Gesture manager: send TapForward event for page forward
  frontend/apps/reader/modules/readergesture.lua
Labels: bug

#4657 [UX] Gesture manager: add action - go to latest bookmark
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#4660 [UX] Gesture manager: more multiswipe defaults
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#4662 [UX] Gesture manager: add north west = folder up as file manager default
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#4661 [UX] Alternative update message when ota_version < local_version
  frontend/ui/otamanager.lua
Labels: UX

#4664 [UX] Gesture manager: add action - show frontlight dialog
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#4665 [UX] Gesture manager: add action - show menu
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#4669 [fix] TimeVal: add dbg:guard against incorrect subtraction order
  frontend/device/gesturedetector.lua
  frontend/ui/timeval.lua
  spec/unit/timeval_spec.lua
Labels: bug

#4673 [fix] ReaderGesture: enable/disable multiswipes without restarting
  frontend/apps/reader/modules/readergesture.lua
Labels: bug

#4675 [chore, UX] Migrate Screen menu to MenuSorter & put Screensaver under Screen
  frontend/ui/elements/common_settings_menu_table.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/elements/reader_menu_order.lua
Labels: UX

#4678 [UX] Gesture manager: add action - go to file browser
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#4677 [UX] Introduce Taps & Gestures menu
  frontend/apps/reader/modules/readergesture.lua
  frontend/ui/elements/common_settings_menu_table.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/elements/reader_menu_order.lua
Labels: UX

#4680 [UX] Navigation settings for all devices
  frontend/apps/reader/modules/readergesture.lua
  frontend/ui/elements/common_settings_menu_table.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/elements/reader_menu_order.lua
Labels: UX

#4666 [fix] GestureDetector: add PANINTERVAL
  frontend/apps/reader/modules/readerpaging.lua
  frontend/apps/reader/modules/readerrolling.lua
  frontend/device/gesturedetector.lua
Labels: UX, bug
