Repository koreader/koreader, pull requests merged in 2019-05, with the labels that each got.

#4945 Give more control over CRe margins
  .luacheckrc
  defaults.lua
  frontend/apps/reader/modules/readerdogear.lua
  frontend/apps/reader/modules/readerfooter.lua
  frontend/apps/reader/modules/readertypeset.lua
  frontend/apps/reader/readerui.lua
  frontend/ui/data/creoptions.lua
  frontend/ui/data/optionsutil.lua
  frontend/ui/data/settings_migration.lua
  frontend/ui/data/strings.lua
  frontend/ui/widget/buttonprogresswidget.lua
  frontend/ui/widget/configdialog.lua
  frontend/ui/widget/virtualkeyboard.lua
  reader.lua
  spec/unit/defaults_spec.lua
Labels: UX

#4993 Restore PAGE_MARGIN string
  frontend/ui/data/strings.lua
Labels: bug

#4999 [Kobo] Sync powerd.fl brightness with powerd when toggling the FL
  frontend/device/kobo/powerd.lua
Labels: Kobo

#5011 [fix, UX] Ignore first hold release when keyboard opened with hold
  frontend/ui/widget/button.lua
  frontend/ui/widget/container/inputcontainer.lua
  frontend/ui/widget/inputdialog.lua
  frontend/ui/widget/inputtext.lua
  frontend/ui/widget/virtualkeyboard.lua
Labels: UX, bug

#5012 newsdownloader: rebuild URL on redirect to bare path
  plugins/newsdownloader.koplugin/epubdownloadbackend.lua
Labels: Plugin, bug

#5028 [UX] Update Greek keyboard with swipes & popup
  frontend/ui/data/keyboardlayouts/el_keyboard.lua
  frontend/ui/data/keyboardlayouts/en_keyboard.lua
  frontend/ui/data/keyboardlayouts/keypopup/el_popup.lua
Labels: UX

#5027 [fix] Don't try to save highlight into non-PDF document
  frontend/document/pdfdocument.lua
Labels: bug

#5026 [fix, chore] Abstract filename logic in util.getSafeFilename()
  frontend/apps/reader/modules/readerlink.lua
  frontend/ui/widget/dictquicklookup.lua
  frontend/ui/widget/opdsbrowser.lua
  frontend/util.lua
  plugins/newsdownloader.koplugin/main.lua
  plugins/wallabag.koplugin/main.lua
Labels: bug

#5034 Tweak the Aura viewport
  frontend/device/kobo/device.lua
Labels: Kobo

#5036 [fix] util.getSafeFilename() default to worst-case scenario
  frontend/util.lua
  plugins/wallabag.koplugin/main.lua
Labels: bug

#5040 NewsDownloader: Allow including images when using text from feed
  plugins/newsdownloader.koplugin/epubdownloadbackend.lua
  plugins/newsdownloader.koplugin/main.lua
Labels: Plugin
