Repository koreader/koreader, pull requests merged in 2019-10, with the labels that each got.

#5443 [wallabag] fetch pdf files directly instead of converting them
  plugins/wallabag.koplugin/main.lua
Labels: Plugin

#5451 cre: properly unmark link position markers
  frontend/apps/reader/modules/readerrolling.lua
Labels: bug

#5453 Fix: Crash after change book status page
  frontend/ui/widget/toggleswitch.lua
Labels: bug

#5452 Fix frozen confirmbox when keyboard shown
  frontend/ui/uimanager.lua
Labels: UX

#5450 [spec] Add ToggleSwitch spec stub
  spec/unit/toggleswitch_spec.lua
Labels: bug

#5460 [fix] Try to make screensaver settings slightly less error-prone
  frontend/apps/reader/modules/readermenu.lua
Labels: bug

#5446 Image viewer use the whole screen
  frontend/ui/widget/imageviewer.lua
Labels: UX

#5458 [Android] Ship Noto
  Makefile
Labels: Android

#5428 per directory defaults
  frontend/apps/reader/readerui.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/elements/reader_menu_order.lua
  plugins/docsettingtweak.koplugin/_meta.lua
  plugins/docsettingtweak.koplugin/directory_defaults_template.lua
  plugins/docsettingtweak.koplugin/main.lua
Labels: Plugin

#5463 [Android, fix] Revert slightly more of the Noto business
  frontend/ui/font.lua
Labels: Android, bug

#5442 Show a progress bar at the bottom of the screen
  .luacheckrc
  defaults.lua
  frontend/apps/reader/modules/readerfooter.lua
  frontend/apps/reader/modules/readerpaging.lua
  frontend/ui/widget/progresswidget.lua
  spec/unit/defaults_spec.lua
Labels: UX

#5474 fix typos
  frontend/apps/reader/modules/readerfont.lua
Labels: chore

#5468 [Kobo] Always set the warmth on the KA1
  frontend/device/kobo/powerd.lua
Labels: Kobo, bug

#5440 Support for exporting annotations/bookmark renames
  plugins/evernote.koplugin/clip.lua
Labels: Plugin

#5477 [Kobo] Log the FW/kernel version on crash
  platform/kobo/koreader.sh
Labels: Kobo

#5484 [chore] Make ShellCheck happy
  platform/kobo/koreader.sh
Labels: chore

#5486 Use system font in Pocketbook
  platform/pocketbook/koreader.app
Labels: PocketBook

#5467 [feat] plugins/Wallabag: add ability to set a list of tags to ignore
  plugins/wallabag.koplugin/main.lua
Labels: Plugin

#5491 Fix footer with no_mode and disabled progress bar
  frontend/apps/reader/modules/readerfooter.lua
  frontend/apps/reader/modules/readertypeset.lua
Labels: bug

#5493 show android mountpoint on system stats
  plugins/systemstat.koplugin/main.lua
Labels: Plugin

#5502 [fix, plugin] Remove wakeup task on resume
  plugins/autosuspend.koplugin/main.lua
Labels: Plugin, bug

#5504 Remove uneeded doc_settings:close()
  frontend/document/pdfdocument.lua
  frontend/ui/screensaver.lua
Labels: chore

#5507 [fix] kodev: Allow nightly build to succeed
  Makefile
  kodev
Labels: bug

#5510 [doc] Update InputDialog example
  frontend/ui/widget/inputdialog.lua
Labels: documentation

#5508 UI Changes
  frontend/apps/filemanager/filemanager.lua
  frontend/apps/filemanager/filemanagerutil.lua
  frontend/ui/elements/common_settings_menu_table.lua
  frontend/ui/widget/keyvaluepage.lua
  frontend/ui/widget/menu.lua
  frontend/ui/widget/touchmenu.lua
  plugins/coverbrowser.koplugin/listmenu.lua
  plugins/coverbrowser.koplugin/main.lua
  plugins/goodreads.koplugin/doublekeyvaluepage.lua
Labels: UX

#5517 [fix] GetText: Support Arabic plurals
  frontend/gettext.lua
  spec/unit/gettext_spec.lua
Labels: bug, i18n

#5515 [i18n] Enable Arabic, Esperanto, and Vietnamese
  frontend/ui/language.lua
Labels: i18n

#5525 CoverBrowser: some fixes after #5435
  plugins/coverbrowser.koplugin/listmenu.lua
Labels: Plugin

#5497 open unsupported documents as text
  frontend/apps/filemanager/filemanager.lua
  frontend/apps/reader/readerui.lua
  frontend/document/documentregistry.lua
  frontend/ui/widget/filechooser.lua
Labels: enhancement

#5530 [fix] typo in #5522
  frontend/apps/reader/modules/readertypeset.lua
Labels: chore

#5528 [statistic plugin] Don't generate md5 sum on open document
  plugins/statistics.koplugin/main.lua
Labels: Plugin

#5540 Handle max_width in time widget
  frontend/ui/widget/timewidget.lua
Labels: bug

#5548 [fix, Android] Crash on startup when no homedir is set
  frontend/apps/filemanager/filemanagerutil.lua
Labels: Android, bug

#5546 Fix a deadlock with empty settings
  doc/Building.md
  plugins/docsettingtweak.koplugin/main.lua
Labels: bug

#5551 CoverBrowser: list mode: better default for files_per_page
  plugins/coverbrowser.koplugin/listmenu.lua
  plugins/coverbrowser.koplugin/main.lua
Labels: UX
