Repository koreader/koreader, pull requests merged in 2019-08, with the labels that each got.

#5161 On (really old) Kindles, don't crash if there's no sysfs entry to rea…
  frontend/device/kindle/powerd.lua
Labels: Kindle

#5156 Add vertical edge gesture
  frontend/apps/reader/modules/readerfrontlight.lua
  frontend/apps/reader/modules/readergesture.lua
  frontend/pluginloader.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/elements/reader_menu_order.lua
  plugins/kobolight.koplugin/_meta.lua
  plugins/kobolight.koplugin/demo.png
  plugins/kobolight.koplugin/demo_ka1.png
  plugins/kobolight.koplugin/main.lua
Labels: UX

#5162 Don't use WAL on devices where it's not supported
  frontend/device/generic/device.lua
  frontend/device/kindle/device.lua
  plugins/coverbrowser.koplugin/bookinfomanager.lua
  plugins/statistics.koplugin/main.lua
Labels: Kindle

#5163 Go Big or Go Home!
  frontend/apps/filemanager/filemanager.lua
Labels: UX

#5171 fix "empty folder" when accessing nextcloud webdav
  frontend/apps/cloudstorage/webdavapi.lua
Labels: bug

#5167 Add gesture - show current book statistics
  frontend/apps/reader/modules/readergesture.lua
  plugins/statistics.koplugin/main.lua
Labels: Plugin, enhancement

#5175 Extend the touch zone for up button in touch menu.
  frontend/ui/widget/touchmenu.lua
Labels: UX

#5177 Fix: hold left corner doesn't work properly
  frontend/ui/widget/button.lua
Labels: bug

#5179 Add horizontal edge gestures
  frontend/apps/filemanager/filemanager.lua
  frontend/apps/reader/modules/readergesture.lua
  frontend/ui/widget/menu.lua
Labels: UX

#5170 Change default zoom mode & add warning message for fit page + scroll
  frontend/apps/reader/modules/readerview.lua
  frontend/apps/reader/modules/readerzooming.lua
  spec/unit/readerlink_spec.lua
  spec/unit/readerview_spec.lua
Labels: UX, bug

#5181 Extend edge zones
  frontend/apps/reader/modules/readerfrontlight.lua
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#5183 Add double finger up and down swipe gesture
  frontend/apps/reader/modules/readerfrontlight.lua
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#5185 minor: KoSync: translate some menu text and error message
  plugins/kosync.koplugin/main.lua
Labels: Plugin

#5184 Fix: Zsync -> Subscribe to book share crashes
  plugins/zsync.koplugin/main.lua
Labels: Plugin

#5188 Gesture spread pinch
  frontend/apps/reader/modules/readerfont.lua
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#5189 Fix: conflict horizontal edge gesture with link swipe
  frontend/apps/reader/modules/readergesture.lua
  frontend/apps/reader/modules/readerlink.lua
Labels: UX

#5193 Update for the greek popups
  frontend/ui/data/keyboardlayouts/keypopup/el_popup.lua
Labels: UX

#5195 Status bar alignment
  frontend/apps/reader/modules/readerfooter.lua
Labels: enhancement

#5197 avoid hard-coded path
  kodev
  platform/debian/koreader.sh
Labels: Desktop

#5198 Add missing parentheses
  frontend/device/kobo/device.lua
Labels: Kobo, bug

#5208 Honor the alpha channel in our icon for the About popup
  frontend/ui/elements/common_info_menu_table.lua
  frontend/ui/widget/infomessage.lua
Labels: bug

#5211 Simplify isWifiOn on Kobo
  frontend/device/kobo/device.lua
Labels: Kobo

#5202 Add gesture - poweroff and restart device
  frontend/apps/filemanager/filemanagermenu.lua
  frontend/apps/reader/modules/readergesture.lua
  frontend/apps/reader/modules/readermenu.lua
  frontend/device/android/device.lua
  frontend/device/cervantes/device.lua
  frontend/device/generic/device.lua
  frontend/device/kobo/device.lua
  frontend/device/sony-prstux/device.lua
  frontend/ui/elements/common_info_menu_table.lua
Labels: UX, enhancement

#5203 Some footer tweaks
  frontend/apps/reader/modules/readerfooter.lua
  frontend/util.lua
  spec/unit/readerfooter_spec.lua
  spec/unit/util_spec.lua
Labels: UX

#5223 Remove Polish keyboard
  frontend/ui/data/keyboardlayouts/pl_keyboard.lua
  frontend/ui/widget/virtualkeyboard.lua
Labels: UX

#5225 Move tap x y corner to tap corner submenu
  frontend/apps/reader/modules/readergesture.lua
Labels: UX

#5227 Never full refresh
  frontend/ui/elements/refresh_menu_table.lua
Labels: UX, enhancement

#5217 Simplify readme
  README.md
  doc/Building.md
  doc/Building_targets.md
  doc/Collaborating_with_Git.md
  doc/Development_guide.md
  doc/Unit_tests.md
Labels: documentation

#5231 [fix] Update LDoc config
  doc/config.ld
Labels: bug, documentation

#5220 [Desktop]: Open writable font dir in FM, toggle between system+user and user fonts, fix openLink on mac...
  frontend/apps/reader/modules/readerfont.lua
  frontend/device/generic/device.lua
  frontend/device/sdl/device.lua
  frontend/document/canvascontext.lua
  frontend/fontlist.lua
  frontend/ui/elements/font_settings.lua
  platform/appimage/AppRun
  platform/debian/koreader.sh
Labels: Desktop, enhancement

#5233 Prevent double run genFooterText
  frontend/apps/reader/modules/readerfooter.lua
Labels: bug

#5234 [i18n, feat] Add basic context (msgctxt) support
  frontend/gettext.lua
Labels: enhancement

#5237 [i18n] Switch `make pot` to xgettext
  Makefile
  frontend/ui/data/css_tweaks.lua
Labels: enhancement

#5235 Update Kindle support devices list
  platform/kindle/extensions/koreader/README.txt
Labels: Kindle

#5241 handle OPDS catalog responses accordingly
  frontend/ui/widget/opdsbrowser.lua
Labels: bug

#5242 [CI] Switch to custom xgettext build to extract multiline strings
  .ci/check.sh
  .circleci/config.yml
  frontend/apps/reader/modules/readerdictionary.lua
  frontend/apps/reader/modules/readergesture.lua
  frontend/apps/reader/modules/readerhighlight.lua
  frontend/apps/reader/modules/readerlink.lua
  frontend/apps/reader/modules/readerrolling.lua
  frontend/apps/reader/modules/readerstyletweak.lua
  frontend/apps/reader/modules/readertypeset.lua
  frontend/apps/reader/modules/readerview.lua
  frontend/apps/reader/modules/readerwikipedia.lua
  frontend/apps/reader/modules/readerzooming.lua
  frontend/ui/data/creoptions.lua
  frontend/ui/data/css_tweaks.lua
  frontend/ui/data/optionsutil.lua
  frontend/ui/quickstart.lua
  frontend/ui/widget/configdialog.lua
  frontend/ui/widget/hyphenationlimits.lua
  frontend/util.lua
  plugins/coverbrowser.koplugin/bookinfomanager.lua
  plugins/goodreads.koplugin/main.lua
  plugins/statistics.koplugin/main.lua
  plugins/texteditor.koplugin/main.lua
  plugins/wallabag.koplugin/main.lua
Labels: bug, chore

#5243 [fix, CI] Push developer docs once again
  .ci/after_success.sh
Labels: chore

#5245 Git ignore .directory files
  .gitignore
Labels: chore

#5246 [chore, i18n] Translate "not set"
  frontend/ui/data/optionsutil.lua
Labels: chore

#5248 Fix: Unable to hold top right corner in FileManager
  frontend/apps/filemanager/filemanager.lua
  frontend/ui/widget/iconbutton.lua
Labels: UX, bug

#5256 [fix, i18n] Make two strings translatable
  frontend/apps/reader/modules/readerhighlight.lua
  plugins/statistics.koplugin/main.lua
Labels: bug

#5257 [feat, i18n] Implement ngettext
  Makefile
  frontend/gettext.lua
  frontend/ui/widget/filechooser.lua
  plugins/coverbrowser.koplugin/listmenu.lua
  plugins/evernote.koplugin/main.lua
  spec/unit/gettext_spec.lua
Labels: enhancement

#5258 [chore] Remove executable bit on device/input.lua
  frontend/device/input.lua
Labels: chore

#5260 [spec] Test all gettext codepaths & add support for language with no plurals
  frontend/gettext.lua
  spec/unit/gettext_spec.lua
Labels: chore

#5261 [fix, CI] Forgot to run luacheck
  spec/unit/gettext_spec.lua
Labels: bug

#5267 [chore] Convert a couple more todos
  .ci/check.sh
  frontend/apps/reader/modules/readerrolling.lua
  frontend/device/gesturedetector.lua
  frontend/device/kindle/device.lua
  frontend/document/pdfdocument.lua
  frontend/ui/widget/container/framecontainer.lua
  frontend/ui/widget/linewidget.lua
  frontend/ui/widget/menu.lua
  frontend/ui/widget/textwidget.lua
  plugins/send2ebook.koplugin/main.lua
Labels: chore

#5270 [fix] Remove gettext util dependency
  frontend/gettext.lua
Labels: bug

#5268 [feat] Friendly filename
  .gitignore
  Makefile
Labels: UX, documentation, enhancement

#5272 [fix] Cervantes package generation
  Makefile
Labels: bug

#5266 [fix] Distinguish bookmark/page flipping in menu
  frontend/apps/reader/modules/readerbookmark.lua
  frontend/apps/reader/modules/readerpaging.lua
Labels: bug

#5275 [AppImage] AppImageTool 12
  Makefile
Labels: AppImage

#5273 [chore] Makefile cleanups
  Makefile
Labels: chore

#5276 [UX] Ignore page flipping toggle while bookmark flipping
  frontend/apps/reader/modules/readerpaging.lua
Labels: UX

#5278 [fix, UX] Update kosync login/logout text
  plugins/kosync.koplugin/main.lua
Labels: UX, bug

#5280 [feat, Kobo] Implement shutdown from suspend
  frontend/device/input.lua
  frontend/ui/uimanager.lua
Labels: Kobo, enhancement

#5284 [UX] Treat inverse_reading_order as a proper setting
  frontend/apps/reader/modules/readerpaging.lua
  frontend/apps/reader/modules/readerrolling.lua
  frontend/ui/elements/reader_menu_order.lua
Labels: UX

#5283 [feat] Implement fulltext search direction
  frontend/apps/reader/modules/readersearch.lua
Labels: UX, enhancement

#5282 [feat] Add MuPDF EPUB/FB2 dynamic font size
  frontend/apps/reader/modules/readerconfig.lua
  frontend/apps/reader/modules/readerpaging.lua
  frontend/apps/reader/modules/readerview.lua
  frontend/apps/reader/modules/readerzooming.lua
  frontend/apps/reader/readerui.lua
  frontend/document/document.lua
  frontend/document/pdfdocument.lua
  frontend/ui/data/koptoptions.lua
  frontend/ui/widget/configdialog.lua
Labels: enhancement

#5285 [doc] Add internal documentation references
  doc/Events.md
  frontend/ui/event.lua
Labels: documentation

#5286 [fix] Pass plain link to link:onGotoLink
  frontend/apps/reader/modules/readerhighlight.lua
  frontend/ui/widget/dictquicklookup.lua
Labels: bug

#5287 [fix] Add CanvasContext to wbuilder
  tools/wbuilder.lua
Labels: bug

#5290 [doc] Convert koptinterface comments to LDoc format
  frontend/document/koptinterface.lua
Labels: documentation
