Repository koreader/koreader, pull requests merged in 2020-07, with the labels that each got.

#6341 [fix] Bring kodev cov command in line with kodev test
  kodev
Labels: bug

#6348 allow default FM rotation on init when `Keep FM rotation` is disabled
  frontend/apps/filemanager/filemanager.lua
  reader.lua
Labels: bug

#6366 remove isAllowedScript leftovers
  frontend/apps/filemanager/filemanagercollection.lua
  frontend/document/credocument.lua
  frontend/util.lua
Labels: bug

#6368 WSL extra bits
  doc/Building.md
Labels: documentation

#6292 ReaderGesture: cleanup
  doc/Development_guide.md
  frontend/apps/filemanager/filemanager.lua
  frontend/apps/filemanager/filemanagerfilesearcher.lua
  frontend/apps/filemanager/filemanagermenu.lua
  frontend/apps/reader/modules/readerdictionary.lua
  frontend/apps/reader/modules/readerfont.lua
  frontend/apps/reader/modules/readerfooter.lua
  frontend/apps/reader/modules/readerfrontlight.lua
  frontend/apps/reader/modules/readergesture.lua
  frontend/apps/reader/modules/readerlink.lua
  frontend/apps/reader/modules/readermenu.lua
  frontend/apps/reader/modules/readerpagemap.lua
  frontend/apps/reader/modules/readerpaging.lua
  frontend/apps/reader/modules/readerrolling.lua
  frontend/apps/reader/modules/readertoc.lua
  frontend/apps/reader/readerui.lua
  frontend/device/devicelistener.lua
  frontend/device/input.lua
  frontend/ui/elements/common_info_menu_table.lua
  frontend/ui/elements/common_settings_menu_table.lua
  frontend/ui/elements/screen_rotation_menu_table.lua
  frontend/ui/network/networklistener.lua
  frontend/ui/otamanager.lua
  frontend/ui/widget/filechooser.lua
  plugins/statistics.koplugin/main.lua
  spec/unit/readerfooter_spec.lua
Labels: chore

#6371 Tame a few tests that relied on `pairs` being somewhat deterministic
  frontend/apps/filemanager/lib/md.lua
  frontend/depgraph.lua
  frontend/ui/menusorter.lua
  spec/unit/defaults_spec.lua
  spec/unit/depgraph_spec.lua
  spec/unit/menusorter_spec.lua
  spec/unit/widget_inputcontainer_spec.lua
  spec/unit/widget_menu_spec.lua
Labels: chore

#6400 set FULL_REFRESH_COUNT to a sane value if no pref is set and toggleNi…
  frontend/ui/uimanager.lua
Labels: bug

#6397 remarkable: add more detail to README about launcher
  platform/remarkable/README_remarkable.txt
Labels: documentation

#6403 [fix] MenuSorter: use orderedPairs for orphans
  frontend/ui/menusorter.lua
Labels: bug

#6404 [fix] Use orderedPairs in touch menu item table
  frontend/ui/widget/menu.lua
  spec/unit/widget_menu_spec.lua
Labels: bug

#6363 Fix issues #6362 - ftp corruption of binary files
  frontend/apps/cloudstorage/ftpapi.lua
Labels: bug

#6417 Fake battery status in readerfooter_spec to succeed on devices with batteries
  frontend/device/sdl/powerd.lua
  spec/unit/readerfooter_spec.lua
Labels: chore

#6425 Fix typo
  plugins/wallabag.koplugin/main.lua
Labels: bug

#6423 Don't store document-specific rotation when sticky rotation is enabled
  frontend/apps/reader/modules/readerview.lua
Labels: UX, bug

#6428 allow text to be translated
  frontend/apps/cloudstorage/ftp.lua
  frontend/apps/reader/modules/readerbookmark.lua
  frontend/ui/elements/common_settings_menu_table.lua
Labels: i18n

#6431 [fix] Add plural string for number of books
  plugins/coverbrowser.koplugin/bookinfomanager.lua
Labels: bug, i18n

#6437 [fix] Statistics: allow for proper translation of plural
  plugins/statistics.koplugin/main.lua
Labels: Plugin, i18n

#6452 Update tesseract data files URL
  frontend/apps/reader/modules/readerhighlight.lua
Labels: chore
