Repository koreader/koreader, pull requests merged in 2020-06, with the labels that each got.

#6216 SkimToWidget: fix next/prev bookmark not updating it
  frontend/apps/reader/skimtowidget.lua
Labels: bug

#6218 fix missing glyphs by packaging freefonts again.
  frontend/apps/reader/modules/readerfooter.lua
  platform/debian/do_debian_package.sh
Labels: Desktop, bug

#6195 [UX] Implement hasFewKeys prototype
  frontend/apps/reader/modules/readermenu.lua
  frontend/apps/reader/modules/readerpaging.lua
  frontend/ui/widget/buttondialog.lua
  frontend/ui/widget/buttondialogtitle.lua
  frontend/ui/widget/focusmanager.lua
  frontend/ui/widget/menu.lua
  frontend/ui/widget/touchmenu.lua
Labels: UX

#6229 [fix] Ignore sha2.lua in doc generation
  doc/config.ld
Labels: bug, documentation

#6225 Footer: skip tap lock when needed
  frontend/apps/reader/modules/readerfooter.lua
Labels: bug

#6228 [NewsDownloader] Added an HTML filter through a CSS selector
  plugins/newsdownloader.koplugin/epubdownloadbackend.lua
  plugins/newsdownloader.koplugin/feed_config.lua
  plugins/newsdownloader.koplugin/main.lua
Labels: Plugin

#6238 Allow message to be overlaid on other screensavers
  .gitignore
  frontend/ui/elements/screensaver_menu.lua
  frontend/ui/screensaver.lua
Labels: UX, enhancement

#6240 Ensure feature-parity in ScreenSaver handling on Kindle
  frontend/device/kindle/device.lua
Labels: Kindle, enhancement

#6248 desktop: don't show `which` results on console
  frontend/device/sdl/device.lua
Labels: Desktop

#6260 android: replace default footer margins.
  frontend/apps/reader/modules/readerfooter.lua
Labels: Android

#6258 [doc] Add documentation to optmath
  frontend/optmath.lua
Labels: documentation

#6257 A few footer tweaks
  frontend/apps/reader/modules/readerfooter.lua
Labels: UX, enhancement

#6262 [plugin, UX] Wallabag: aid with setting up missing information
  plugins/wallabag.koplugin/main.lua
Labels: Plugin, UX

#6273 Fix bottom menu item titles truncation
  frontend/ui/widget/configdialog.lua
Labels: bug

#6146 Add chapter title when exporting notes in Evernote(JSON/HTML, remote)
  frontend/apps/reader/modules/readerbookmark.lua
  frontend/apps/reader/modules/readerhighlight.lua
  frontend/apps/reader/modules/readertoc.lua
  plugins/evernote.koplugin/clip.lua
  plugins/evernote.koplugin/note.tpl
Labels: Plugin

#6279 [chore] Rename 'More plugins' to 'More tools'
  frontend/ui/elements/common_info_menu_table.lua
Labels: chore

#6280 Device abstraction
  frontend/apps/filemanager/filemanager.lua
  frontend/apps/filemanager/filemanagerutil.lua
  frontend/device/android/device.lua
  frontend/device/cervantes/device.lua
  frontend/device/generic/device.lua
  frontend/device/kindle/device.lua
  frontend/device/kobo/device.lua
  frontend/device/pocketbook/device.lua
  frontend/device/remarkable/device.lua
  frontend/device/sdl/device.lua
  frontend/ui/elements/common_info_menu_table.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/elements/reader_menu_order.lua
Labels: chore

#6177 unified calibre plugin
  .luacheckrc
  defaults.lua
  frontend/apps/filemanager/filemanager.lua
  frontend/apps/filemanager/filemanagermenu.lua
  frontend/apps/filemanager/filemanagersearch.lua
  frontend/apps/reader/modules/readergesture.lua
  frontend/device/kindle/device.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/elements/reader_menu_order.lua
  frontend/util.lua
  plugins/calibre.koplugin/_meta.lua
  plugins/calibre.koplugin/extensions.lua
  plugins/calibre.koplugin/main.lua
  plugins/calibre.koplugin/metadata.lua
  plugins/calibre.koplugin/search.lua
  plugins/calibre.koplugin/wireless.lua
  plugins/calibrecompanion.koplugin/_meta.lua
  plugins/calibrecompanion.koplugin/main.lua
  spec/unit/defaults_spec.lua
Labels: Plugin, enhancement

#6282 move some 'permanent' settings inside more_tools
  frontend/ui/elements/common_info_menu_table.lua
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/elements/reader_menu_order.lua
Labels: UX

#6275 Startup Scripts
  Makefile
  platform/android/llapp_main.lua
Labels: Android

#6106 Dispatcher: for profiles & gestures
  frontend/dispatcher.lua
  frontend/ui/elements/reader_menu_order.lua
  plugins/profiles.koplugin/_meta.lua
  plugins/profiles.koplugin/main.lua
Labels: Plugin

#6283 More robust way to detect our own path on Kobo
  platform/kobo/koreader.sh
Labels: Kobo

#6287 migrate user directories after update
  platform/android/llapp_main.lua
Labels: Android

#6291 Migrate to new issue templates workflow
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: chore

#6294 [plugin] Add menu separators to Evernote menu
  plugins/evernote.koplugin/main.lua
Labels: Plugin, UX

#6295 Translator: Add definition of the word to the translation
  frontend/ui/translator.lua
Labels: enhancement

#6289 [doc] Add some tips about GitHub PR refs
  doc/Collaborating_with_Git.md
Labels: documentation

#6288 Add the possibility run shell scripts from filemanager on android
  frontend/apps/filemanager/filemanager.lua
  frontend/device/android/device.lua
  frontend/device/generic/device.lua
  frontend/util.lua
Labels: Android

#6312 Add PocketBook 614W (Basic 3) definition
  frontend/device/pocketbook/device.lua
Labels: PocketBook

#6315 [feat] FocusManager: wrap around horizontally
  frontend/ui/widget/focusmanager.lua
Labels: UX

#6318 [UX] Add left to close to ConfigDialog for hasFewKeys
  frontend/ui/widget/configdialog.lua
Labels: UX

#6307 [chore, plugin] Simplify Wallabag http.request handling
  plugins/wallabag.koplugin/main.lua
Labels: chore

#6308 EvernoteOAuth set logger
  plugins/evernote.koplugin/main.lua
Labels: Plugin

#6323 Tests: make sure files are deleted
  spec/unit/document_registry_spec.lua
Labels: chore

#6320 [plugin] Wallabag: Make remove from history consistent with deletion
  plugins/wallabag.koplugin/main.lua
Labels: Plugin

#6324 Dispatcher: fix table
  frontend/dispatcher.lua
Labels: bug

#6322 [UX] Move double tap to gesture manager
  frontend/apps/reader/modules/readergesture.lua
  frontend/apps/reader/modules/readerpaging.lua
  frontend/apps/reader/modules/readerrolling.lua
  frontend/apps/reader/modules/readerzooming.lua
  frontend/apps/reader/readerui.lua
Labels: UX

#6333 [i18n] Add support for fledgling Hebrew translation
  frontend/gettext.lua
  frontend/ui/language.lua
Labels: i18n

#6335 [feat] Add text/html to OPDSBrowser
  frontend/ui/widget/opdsbrowser.lua
Labels: enhancement

#6334 [chore] Simplify OPDSBrowser http.request handling
  frontend/ui/widget/opdsbrowser.lua
Labels: chore
