Repository koreader/koreader, pull requests merged in 2020-01, with the labels that each got.

#5719 [fix] Various minor string issues
  frontend/apps/filemanager/filemanagersearch.lua
  plugins/SSH.koplugin/main.lua
  plugins/coverbrowser.koplugin/main.lua
Labels: bug, i18n

#5720 [chore] Ellipsis instead of dots
  frontend/ui/uimanager.lua
Labels: chore

#5718 [fix] Update hardcoded gettext workaround for Romanian
  frontend/gettext.lua
Labels: bug, i18n

#5705 Option to change page gap in continuous mode
  frontend/apps/reader/modules/readerview.lua
  frontend/ui/data/koptoptions.lua
  frontend/ui/data/strings.lua
Labels: enhancement

#5734 [chore] Prevent useless POT updates
  .ci/after_success.sh
Labels: chore

#5742 PicDocuments: fix crash on hold + pan
  frontend/document/document.lua
Labels: bug

#5736 Footer font size
  .luacheckrc
  defaults.lua
  frontend/apps/reader/modules/readerfooter.lua
  spec/unit/defaults_spec.lua
Labels: UX

#5744 [plugin] fix netsh command
  plugins/evernote.koplugin/main.lua
Labels: Plugin

#5745 [android]: share text with other apps
  frontend/apps/reader/modules/readerhighlight.lua
  frontend/device/android/device.lua
  frontend/device/generic/device.lua
Labels: Android

#5749 LoginDialog: fix crash on focus switch
  frontend/ui/widget/logindialog.lua
Labels: bug

#5743 [doc] Add ragel to build prerequisites
  doc/Building.md
Labels: documentation

#5758 Unbreak OTA on Kindle
  Makefile
  platform/kindle/koreader.sh
  platform/kindle/libkohelper.sh
Labels: Kindle, bug

#5765 fix, confusing info/error message when exporting bookmarks
  plugins/evernote.koplugin/main.lua
Labels: Plugin

#5569 Keyboard for Arabic and languages with Arabic script, initial release
  frontend/ui/data/keyboardlayouts/ar_AA_keyboard.lua
  frontend/ui/data/keyboardlayouts/keypopup/ar_AA_popup.lua
  frontend/ui/widget/virtualkeyboard.lua
Labels: UX

#5785 Show or hide hidden folders in folder shortcut chooser
  frontend/apps/filemanager/filemanagershortcuts.lua
Labels: bug

#5774 [fix, plugin] Evernote exporter only writes one documents clippings when txt export used, rest is ignored
  plugins/evernote.koplugin/main.lua
  spec/unit/evernote_plugin_main_spec.lua
Labels: Plugin
