Repository koreader/koreader, pull requests merged in 2020-02, with the labels that each got.

#5809 [CI] Add curly braces check
  .ci/after_success.sh
  .ci/before_install.sh
  .ci/check.sh
  .ci/common.sh
  .ci/helper_luarocks.sh
  .ci/helper_shellchecks.sh
  .ci/install.sh
  .shellcheckrc
  kodev
  platform/appimage/AppRun
  platform/cervantes/disable-usbms.sh
  platform/cervantes/enable-usbms.sh
  platform/cervantes/koreader-standalone.sh
  platform/debian/do_debian_package.sh
  platform/debian/koreader.sh
  platform/kindle/extensions/koreader/bin/koreader-ext.sh
  platform/kobo/enable-wifi.sh
  platform/kobo/koreader.sh
  platform/pocketbook/koreader.app
  platform/ubuntu-touch/koreader.sh
  plugins/backgroundrunner.koplugin/luawrapper.sh
  plugins/backgroundrunner.koplugin/wrapper.sh
Labels: chore

#5807 [i18n] GetText: ignore fuzzy strings
  frontend/gettext.lua
  spec/unit/gettext_spec.lua
Labels: i18n

#5811 [doc] Update donation info
  README.md
Labels: documentation

#5815 [chore] Replace ... with … (ellipsis)
  frontend/apps/filemanager/filemanager.lua
  frontend/apps/filemanager/filemanagercollection.lua
Labels: chore

#5823 Add “searchable” capabilities to OPDS catalogs
  frontend/ui/widget/opdsbrowser.lua
Labels: enhancement

#5828 Remarkable port
  Makefile
  frontend/apps/filemanager/filemanagerutil.lua
  frontend/device.lua
  frontend/device/generic/device.lua
  frontend/device/remarkable/device.lua
  frontend/device/remarkable/event_map.lua
  frontend/device/remarkable/powerd.lua
  frontend/ui/otamanager.lua
  frontend/ui/uimanager.lua
  kodev
  platform/remarkable/README_remarkable.txt
  platform/remarkable/button-listen.service
  platform/remarkable/koreader.service
  platform/remarkable/koreader.sh
Labels: enhancement, reMarkable

#5829 [CI] Ignore unscaled size check on mt_width/height
  frontend/device/remarkable/device.lua
Labels: reMarkable

#5827 [chore] FileChooser: use "traditional" for loop for ~20% better performance
  frontend/ui/widget/filechooser.lua
Labels: chore

#5834 A couple of minor remarkable port fixes
  frontend/device/remarkable/device.lua
  platform/remarkable/koreader.sh
Labels: reMarkable

#5820 skimto: add beginning and end as hold callback
  frontend/apps/reader/modules/readerbookmark.lua
  frontend/apps/reader/skimtowidget.lua
Labels: UX

#5846 [fix] More accurate count in FileChooser
  frontend/ui/widget/filechooser.lua
Labels: bug

#5839 Add Remarkable to README.md
  README.md
Labels: documentation

#5808 Add some basic info on using ffi-cdecl
  doc/Porting.md
Labels: documentation

#5853 Actually ship the Cervantes version of spinning_zsync
  Makefile
Labels: reMarkable

#5849 Footer: bold font option
  frontend/apps/reader/modules/readerfooter.lua
Labels: UX

#5854 Statistics: new Calendar view
  frontend/ui/widget/container/inputcontainer.lua
  frontend/ui/widget/overlapgroup.lua
  plugins/statistics.koplugin/calendarview.lua
  plugins/statistics.koplugin/main.lua
Labels: Plugin, enhancement

#5860 Get rid of the old PB TC
  Makefile
  kodev
Labels: PocketBook

#5885 continuous: do not limit visible area to page area
  frontend/apps/reader/modules/readerview.lua
  spec/unit/readerlink_spec.lua
  spec/unit/readerview_spec.lua
Labels: bug

#5739 add "message at top of screen" screensaver
  frontend/ui/elements/screensaver_menu.lua
  frontend/ui/screensaver.lua
Labels: enhancement

#5890 Add support for PocketBook InkPad X.
  frontend/device/pocketbook/device.lua
Labels: PocketBook

#5891 macOS build info tweaks
  doc/Building.md
Labels: documentation

#5889 avoid writting to read-only pdfs
  frontend/apps/reader/modules/readerhighlight.lua
  frontend/document/pdfdocument.lua
Labels: bug

#5898 [i18n] allow translation of time (12/24-hours formats)
  frontend/apps/reader/modules/readerfooter.lua
  frontend/ui/widget/touchmenu.lua
Labels: i18n
