Repository koreader/koreader, pull requests merged in 2020-11, with the labels that each got.

#6857 create ota dir
  datastorage.lua
Labels: Android, AppImage, bug

#6874 [fix] Always initiate empty context table
  frontend/gettext.lua
Labels: bug

#6882 sdl: resize FM
  frontend/device/sdl/device.lua
Labels: Desktop, bug

#6880 [Kobo] Don't attempt to restart Nickel when asking for a reboot/shutdown
  frontend/ui/uimanager.lua
  platform/kobo/koreader.sh
Labels: Kobo, bug, firmware

#6887 android: fix dict overrides
  frontend/device/android/device.lua
  frontend/device/thirdparty.lua
Labels: Android, bug

#6897 Remove leftover and correct info message on empty fallback
  plugins/coverimage.koplugin/main.lua
Labels: i18n

#6905 Kobo, Mk.5: Tweak CPU frequency scaling
  .ci/helper_shellchecks.sh
  .ci/install.sh
  platform/kobo/disable-wifi.sh
  platform/kobo/enable-wifi.sh
  platform/kobo/koreader.sh
  platform/kobo/nickel.sh
Labels: Kobo, firmware

#6906 Enable Cover-Image on Remarkable and PocketBook
  frontend/device/remarkable/device.lua
  plugins/coverimage.koplugin/main.lua
Labels: Plugin

#6921 Get rid of ui/data/strings.lua
  frontend/ui/data/creoptions.lua
  frontend/ui/data/koptoptions.lua
  frontend/ui/data/strings.lua
  frontend/ui/elements/screen_rotation_menu_table.lua
Labels: chore

#6927 [chore, i18n] Remove extra quotation marks
  frontend/apps/reader/modules/readerzooming.lua
Labels: chore, i18n

#6928 [chore] Don't translate numbers
  frontend/ui/data/koptoptions.lua
Labels: chore

#6930 Fix #6929
  frontend/apps/reader/modules/readerpaging.lua
Labels: bug
