Repository koreader/koreader, pull requests merged in 2021-06, with the labels that each got.

#7840 Add option to change checksum method in KOSync to be Binary or Filename based
  plugins/kosync.koplugin/main.lua
Labels: Plugin, enhancement

#7880 InputText correct misprint
  frontend/ui/widget/inputtext.lua
Labels: bug

#7911 KeyboardLayoutDialog movable
  frontend/ui/widget/keyboardlayoutdialog.lua
Labels: bug

#7906 Greek keyboard update: add more diacritics (polytonic)
  frontend/ui/data/keyboardlayouts/el_keyboard.lua
  frontend/ui/data/keyboardlayouts/keypopup/el_popup.lua
Labels: enhancement
