Repository koreader/koreader, pull requests merged in 2021-02, with the labels that each got.

#7225 Georgian keyboard
  frontend/ui/data/keyboardlayouts/ka_keyboard.lua
  frontend/ui/data/keyboardlayouts/keypopup/ka_popup.lua
  frontend/ui/language.lua
  frontend/ui/widget/virtualkeyboard.lua
Labels: UX

#7216 Remarkable1 wifi
  frontend/device/remarkable/device.lua
  platform/remarkable/disable-wifi.sh
  platform/remarkable/enable-wifi.sh
Labels: enhancement, reMarkable

#7239 [chore] Properly set CoverImage menu order
  frontend/ui/elements/reader_menu_order.lua
Labels: chore

#7222 Persian keyboard
  frontend/ui/data/keyboardlayouts/fa_keyboard.lua
  frontend/ui/data/keyboardlayouts/keypopup/fa_popup.lua
  frontend/ui/widget/virtualkeyboard.lua
Labels: UX

#7253 [chore] Fix a few Persian keyboard luacheck issues
  frontend/ui/data/keyboardlayouts/fa_keyboard.lua
  frontend/ui/data/keyboardlayouts/keypopup/fa_popup.lua
Labels: chore

#7237 move opds to plugin
  plugins/opds.koplugin/_meta.lua
  plugins/opds.koplugin/main.lua
  plugins/opds.koplugin/opdsbrowser.lua
  plugins/opds.koplugin/opdscatalog.lua
  plugins/opds.koplugin/opdsparser.lua
  spec/unit/opds_spec.lua
Labels: Plugin

#7292 [chore] Fix up util.stringStartsWith/stringEndsWith LDoc comments
  frontend/util.lua
Labels: chore, documentation

#7291 [fix] Remove OPDS menu entry from FilemanagerMenu
  frontend/apps/filemanager/filemanagermenu.lua
  frontend/ui/elements/filemanager_menu_order.lua
Labels: Plugin, bug

#7328 Standardize directory/folder to folder
  frontend/apps/cloudstorage/cloudstorage.lua
  frontend/apps/filemanager/filemanager.lua
  frontend/apps/filemanager/filemanagermenu.lua
  frontend/apps/reader/modules/readerwikipedia.lua
  frontend/ui/cloudmgr.lua
  frontend/ui/elements/common_settings_menu_table.lua
  frontend/ui/quickstart.lua
  frontend/ui/screensaver.lua
  frontend/ui/widget/pathchooser.lua
  frontend/ui/widget/screenshoter.lua
  plugins/calibre.koplugin/main.lua
  plugins/movetoarchive.koplugin/main.lua
  plugins/newsdownloader.koplugin/main.lua
  plugins/send2ebook.koplugin/main.lua
Labels: i18n

#7367 Add Bulgarian keyboard layout.
  frontend/ui/data/keyboardlayouts/bg_keyboard.lua
  frontend/ui/widget/virtualkeyboard.lua
Labels: UX
