Repository koreader/koreader, pull requests merged in 2021-09, with the labels that each got.

#8146 calibre: gui to choose default extension
  plugins/calibre.koplugin/extensions.lua
  plugins/calibre.koplugin/main.lua
  plugins/calibre.koplugin/wireless.lua
Labels: enhancement, Plugin

#8169 Minor script tweaks
  frontend/device/kobo/device.lua
  platform/kobo/disable-wifi.sh
  platform/kobo/enable-wifi.sh
  platform/kobo/koreader.sh
  platform/kobo/nickel.sh
Labels: Kobo, chore

#8174 Readerhighlight: notification on changing style via gesture
  frontend/apps/reader/modules/readerhighlight.lua
Labels: bug

#8177 Readme: Tame down expectations
  README.md
Labels: documentation

#8198 DocCache: Allow disabling it (again)
  frontend/cache.lua
  frontend/document/doccache.lua
Labels: bug

#8210 Fix OPDS plugin bug wherein Arxiv PDF document acquisition URLs are not given a callback to download.
  plugins/opds.koplugin/opdsbrowser.lua
Labels: Plugin, OPDS

#8145 Fixes and changes to newsdownloader.koplugin
  plugins/newsdownloader.koplugin/feed_config.lua
  plugins/newsdownloader.koplugin/feed_view.lua
  plugins/newsdownloader.koplugin/main.lua
Labels: Plugin

#8214 Newsdownloader: Fix warnings from luacheck
  plugins/newsdownloader.koplugin/feed_view.lua
  plugins/newsdownloader.koplugin/main.lua
Labels: chore

#8215 Dispatcher: adjust "screen and lights" to style guide
  frontend/dispatcher.lua
Labels: Plugin, chore

#8217 Help text fixes
  frontend/apps/reader/modules/readersearch.lua
  frontend/ui/data/css_tweaks.lua
Labels: bug, i18n

#8220 Fix undeclared variable error
  plugins/newsdownloader.koplugin/epubdownloadbackend.lua
  plugins/newsdownloader.koplugin/feed_view.lua
Labels: bug, Plugin

#8223 Input dialogs: keep size in rotation
  frontend/apps/cloudstorage/dropbox.lua
  frontend/apps/cloudstorage/ftp.lua
  frontend/apps/cloudstorage/webdav.lua
  frontend/apps/filemanager/filemanagerfilesearcher.lua
  frontend/apps/filemanager/filemanagersetdefaults.lua
  frontend/apps/reader/modules/readersearch.lua
  frontend/ui/widget/inputdialog.lua
  frontend/ui/widget/multiinputdialog.lua
  plugins/calibre.koplugin/search.lua
  plugins/opds.koplugin/opdsbrowser.lua
  plugins/perceptionexpander.koplugin/main.lua
  plugins/terminal.koplugin/main.lua
  plugins/wallabag.koplugin/main.lua
Labels: UX

#8233 Fontlist: disable/enable some Kindle fonts
  frontend/fontlist.lua
Labels: Kindle

#8232 Fix segfault on exit after opening fb2.zip
  frontend/document/credocument.lua
Labels: bug

#8129 [plugin] ~~From dusk till dawn~~ Auto-warmth
  frontend/ui/elements/filemanager_menu_order.lua
  frontend/ui/elements/reader_menu_order.lua
  frontend/ui/uimanager.lua
  frontend/ui/widget/doublespinwidget.lua
  frontend/ui/widget/spinwidget.lua
  frontend/util.lua
  plugins/autowarmth.koplugin/_meta.lua
  plugins/autowarmth.koplugin/main.lua
  plugins/autowarmth.koplugin/suntime.lua
Labels: Plugin

#8261 Kobo: Don't leak fds in isWifiOn
  frontend/device/kobo/device.lua
Labels: bug

#8154 [frontlight, kobo, cervantes] Remove auto_warmth
  frontend/device/cervantes/powerd.lua
  frontend/device/devicelistener.lua
  frontend/device/kobo/nickel_conf.lua
  frontend/device/kobo/powerd.lua
  frontend/ui/data/onetime_migration.lua
  frontend/ui/widget/frontlightwidget.lua
Labels: Kobo, Cervantes

#8264 Autowarmth: Make Information in easy mode more beautiful
  plugins/autowarmth.koplugin/main.lua
Labels: Plugin

#8267 [chore] NewsDownloader: remove stray space
  plugins/newsdownloader.koplugin/main.lua
Labels: chore

#8268 [chore] NewsDownloader: various minor string fixes
  plugins/newsdownloader.koplugin/main.lua
Labels: chore
