Repository koreader/koreader, pull requests merged in 2021-05, with the labels that each got.

#7635 Text editor: new 'Clean text editor history' etc.
  plugins/texteditor.koplugin/main.lua
Labels: Plugin

#7655 Fix typo
  frontend/device/android/device.lua
Labels: chore

#7658 FileManager/ReaderUI: Clarify the current instance accessor
  frontend/apps/filemanager/filemanager.lua
  frontend/apps/reader/readerui.lua
  frontend/ui/widget/filechooser.lua
  plugins/opds.koplugin/opdscatalog.lua
  reader.lua
Labels: chore

#7669 ReaderToc: option to show a dotted line
  frontend/apps/reader/modules/readerpagemap.lua
  frontend/apps/reader/modules/readertoc.lua
  frontend/ui/elements/reader_menu_order.lua
  frontend/ui/widget/menu.lua
Labels: UX

#7668 [plugin] Wallabag: different timeouts for API calls vs file downloads
  plugins/wallabag.koplugin/main.lua
Labels: Plugin

#7674 Fix docs
  plugins/coverimage.koplugin/main.lua
Labels: bug, chore

#7664 Geom: nil guard a few rect methods
  frontend/apps/filemanager/filemanager.lua
  frontend/apps/reader/readerui.lua
  frontend/device/generic/device.lua
  frontend/ui/geometry.lua
  frontend/ui/widget/configdialog.lua
  spec/unit/device_spec.lua
Labels: bug

#7678 Fix stupid typo
  plugins/coverimage.koplugin/main.lua
Labels: chore

#7677 [doc] Documentation stub for Dbg module
  frontend/dbg.lua
Labels: documentation

#7682 move SDL check to the end of Device's probe function
  frontend/device.lua
Labels: chore

#7684 PB: Unconditionally disable HW rotation on B288 SoC
  frontend/apps/filemanager/filemanagermenu.lua
  frontend/device/pocketbook/device.lua
Labels: PocketBook, firmware

#7700 ReaderHighlight: nil guard a few self.hold_pos accesses
  frontend/apps/reader/modules/readerhighlight.lua
Labels: bug

#7705 [CoverImage] Use blksize for size of cached files
  plugins/coverimage.koplugin/main.lua
Labels: Plugin

#7701 InputDialog: add search
  frontend/ui/widget/inputdialog.lua
  frontend/ui/widget/inputtext.lua
Labels: UX

#7714 [lang] Fix minor inconsistency
  frontend/ui/widget/inputdialog.lua
Labels: i18n

#7728 ReaderZooming: Deal with some more fallout of the new zoom modes
  frontend/apps/reader/modules/readerzooming.lua
  frontend/ui/data/creoptions.lua
  frontend/ui/data/koptoptions.lua
  frontend/ui/data/onetime_migration.lua
Labels: bug

#7733 ReaderStatus: Don't crash in EndOfDocument actions that *immediately*…
  frontend/apps/reader/modules/readerstatus.lua
Labels: bug

#7730 VirtualKeyboard: move cursor with holding left/right arrows
  frontend/ui/widget/inputtext.lua
  frontend/ui/widget/virtualkeyboard.lua
Labels: UX

#7731 Enable bomb crash screen on Cervantes
  platform/cervantes/koreader.sh
Labels: Cervantes

#7744 Events: Never stop propagating CloseWidget
  frontend/ui/uimanager.lua
  frontend/ui/widget/datewidget.lua
  frontend/ui/widget/dictquicklookup.lua
  frontend/ui/widget/doublespinwidget.lua
  frontend/ui/widget/frontlightwidget.lua
  frontend/ui/widget/imageviewer.lua
  frontend/ui/widget/infomessage.lua
  frontend/ui/widget/keyboardlayoutdialog.lua
  frontend/ui/widget/linkbox.lua
  frontend/ui/widget/naturallightwidget.lua
  frontend/ui/widget/notification.lua
  frontend/ui/widget/openwithdialog.lua
  frontend/ui/widget/qrmessage.lua
  frontend/ui/widget/screensaverwidget.lua
  frontend/ui/widget/skimtowidget.lua
  frontend/ui/widget/spinwidget.lua
  frontend/ui/widget/textviewer.lua
  frontend/ui/widget/timewidget.lua
  frontend/ui/widget/trapwidget.lua
  frontend/ui/widget/virtualkeyboard.lua
Labels: bug

#7753 android: minor fixes
  frontend/device/android/device.lua
Labels: Android

#7768 OPDSParser: Attempt to preserve data from content tags *without* breaking luxl
  plugins/opds.koplugin/opdsparser.lua
Labels: Plugin

#7751 VirtualKeyboard: hide the keyboard with the hold on 'arrow down'
  frontend/ui/widget/inputdialog.lua
  frontend/ui/widget/inputtext.lua
  frontend/ui/widget/virtualkeyboard.lua
Labels: UX
