Repository koreader/koreader, pull requests merged in 2021-03, with the labels that each got.

#7368 WiFi: Handle inconsistent states a tad better.
  frontend/ui/network/manager.lua
  frontend/ui/widget/networksetting.lua
Labels: Kobo, bug

#7386 A few more directory to folder
  frontend/ui/widget/pathchooser.lua
  plugins/opds.koplugin/opdsbrowser.lua
Labels: chore

#7380 OPDS: Parse Open Search Definition for feeds that support it
  plugins/opds.koplugin/opdsbrowser.lua
  plugins/opds.koplugin/opdsparser.lua
  spec/unit/opds_spec.lua
Labels: enhancement

#7359 Add a couple of modern android dicts
  frontend/device/android/device.lua
Labels: Android

#7162 Account for result pagination when fetching notes or notebooks from Joplin API
  plugins/evernote.koplugin/JoplinClient.lua
Labels: Plugin

#7395 Hold "Wi-Fi" menu to show network selection instead of auto-connecting
  frontend/device/kobo/device.lua
  frontend/device/sony-prstux/device.lua
  frontend/ui/network/manager.lua
Labels: reMarkable

#7408 SkimToWidget: swap '1' and '10' buttons
  frontend/ui/widget/skimtowidget.lua
Labels: UX

#7416 Use PluginShare to share the keepalive state
  plugins/keepalive.koplugin/main.lua
Labels: Plugin

#7443 TOC settings: fix ticks disappearing
  frontend/apps/reader/modules/readertoc.lua
Labels: bug

#7421 Add Lua 5.1 to sample Debubuntu apt-get command
  doc/Building.md
Labels: documentation

#7463 ReaderZooming: Fix defaults handling
  frontend/apps/reader/modules/readercropping.lua
  frontend/apps/reader/modules/readerzooming.lua
  frontend/ui/data/creoptions.lua
  frontend/ui/data/koptoptions.lua
  frontend/ui/widget/configdialog.lua
Labels: bug

#7466 ReaderFooter: Workaround a bad interaction with ReaderHighlight related to hold handlers
  frontend/apps/reader/modules/readerfooter.lua
Labels: bug
