Repository koreader/koreader, pull requests merged in 2021-11, with the labels that each got.

#8409 [fix, plugin] Gestures migration: check if setting exists instead of …
  plugins/gestures.koplugin/migration.lua
Labels: bug, Plugin

#8399 readerhighlight: ignore cases where no text is selected
  frontend/apps/reader/modules/readerhighlight.lua
Labels: bug

#8434 [Autowarmth plugin] Fix sanity check for longitude
  plugins/autowarmth.koplugin/suntime.lua
Labels: bug, Plugin

#8438 kopt: correctly handle CJK character detection for space insertion
  frontend/document/koptinterface.lua
Labels: bug

#8441 Display OPDS download titles if available
  plugins/opds.koplugin/opdsbrowser.lua
  spec/unit/opds_spec.lua
Labels: Plugin

#8444 Fix typo in ListView doc
  frontend/ui/widget/listview.lua
Labels: documentation

#8460 [chore] Fix a few luacheck errors
  frontend/apps/reader/modules/readerhighlight.lua
  frontend/apps/reader/modules/readerpaging.lua
  frontend/apps/reader/modules/readerrolling.lua
Labels: chore

#8461 [chore] Fix a few luacheck errors
  frontend/apps/reader/modules/readerdictionary.lua
  frontend/ui/elements/common_exit_menu_table.lua
  frontend/ui/elements/common_info_menu_table.lua
Labels: chore

#8464 [bug] Don't translate empty strings
  frontend/apps/reader/modules/readerfooter.lua
Labels: bug

#8465 [chore] Fix "Compact items" capitalization
  frontend/apps/reader/modules/readerfooter.lua
Labels: chore

#8466 [chore] Change "filebrowser" to "file browser"
  frontend/ui/elements/common_settings_menu_table.lua
Labels: chore

#8471 Kindle: remove zsync plugin iptables rules
  platform/kindle/koreader.sh
Labels: Kindle, chore

#8489 [i18n] Add context to various non/auto/small/medium/large
  frontend/ui/data/creoptions.lua
  frontend/ui/data/koptoptions.lua
Labels: i18n
