Repository koreader/koreader, pull requests merged in 2021-12, with the labels that each got.

#8425 Add documentation for dialog widgets
  frontend/ui/geometry.lua
  frontend/ui/widget/confirmbox.lua
  frontend/ui/widget/datetimewidget.lua
  frontend/ui/widget/imagewidget.lua
  frontend/ui/widget/inputdialog.lua
  frontend/ui/widget/multiinputdialog.lua
Labels: documentation

#8498 ConfigDialog: fix set as default with spinwidgets
  frontend/ui/widget/configdialog.lua
Labels: bug

#8506 [chore, CI] Remove empty whitespace
  frontend/ui/widget/doublespinwidget.lua
Labels: chore

#8510 [i18n] Add context to CSS style vs highlight style
  frontend/apps/reader/modules/readerhighlight.lua
  frontend/apps/reader/modules/readertypeset.lua
Labels: i18n

#8511 [fix] gettext: don't replace backslash characters
  frontend/gettext.lua
Labels: bug, i18n

#8502 [autowarmth, plugin] use date time widget, optimize
  plugins/autowarmth.koplugin/main.lua
  plugins/autowarmth.koplugin/suntime.lua
Labels: Plugin

#8507 [fix] Use XDG_CONFIG_HOME on Linux
  datastorage.lua
Labels: bug, Desktop

#8517 docsettings: fix open/delete file with empty name
  frontend/docsettings.lua
Labels: bug

#8519 [i18n] Add context to "Update"
  frontend/ui/otamanager.lua
Labels: i18n

#8529 SpinWidget fix enable/disable OK button
  frontend/ui/widget/numberpickerwidget.lua
  frontend/ui/widget/spinwidget.lua
Labels: bug

#8539 Trapper: fix doc
  frontend/ui/trapper.lua
Labels: documentation, chore

#8567 File browser select mode fix (disable long-press)
  frontend/apps/filemanager/filemanager.lua
  frontend/ui/widget/filechooser.lua
Labels: bug

#8573 ReaderHighlight: unlock "View HTML"
  frontend/apps/reader/modules/readerhighlight.lua
Labels: bug

#8564 Menu widget: add extra (left) title button
  frontend/ui/widget/button.lua
  frontend/ui/widget/iconbutton.lua
  frontend/ui/widget/menu.lua
Labels: UX

#8548 Add Readwise.io support to highlight exporter plugin
  plugins/exporter.koplugin/ReadwiseClient.lua
  plugins/exporter.koplugin/clip.lua
  plugins/exporter.koplugin/main.lua
Labels: Plugin

#8565 [Coverimage, plugin] Clean up, typo
  plugins/coverimage.koplugin/main.lua
Labels: Plugin

#8551 Handle newlines in HTML highlight export
  plugins/exporter.koplugin/note.tpl
Labels: Plugin

#8582 [fix] batterystat: change per hour
  plugins/batterystat.koplugin/main.lua
Labels: bug, Plugin

#8592 Exporter plugin: html template fix
  plugins/exporter.koplugin/note.tpl
Labels: Plugin
