Repository koreader/koreader, pull requests merged in 2022-05, with the labels that each got.

#9061 Cloudstorage WebDAV: fix leading slash for root folder
  frontend/apps/cloudstorage/webdavapi.lua
Labels: bug

#9041 TitleBar left and right buttons navigation on non-touch devices
  frontend/apps/filemanager/filemanager.lua
  frontend/ui/widget/filechooser.lua
  frontend/ui/widget/focusmanager.lua
  frontend/ui/widget/inputtext.lua
  frontend/ui/widget/menu.lua
  frontend/ui/widget/titlebar.lua
  plugins/coverbrowser.koplugin/covermenu.lua
  plugins/coverbrowser.koplugin/mosaicmenu.lua
Labels: enhancement, NT

#8944 Exporter plugin refactor
  plugins/exporter.koplugin/JoplinClient.lua
  plugins/exporter.koplugin/ReadwiseClient.lua
  plugins/exporter.koplugin/base.lua
  plugins/exporter.koplugin/clip.lua
  plugins/exporter.koplugin/main.lua
  plugins/exporter.koplugin/target/html.lua
  plugins/exporter.koplugin/target/joplin.lua
  plugins/exporter.koplugin/target/json.lua
  plugins/exporter.koplugin/target/readwise.lua
  plugins/exporter.koplugin/target/text.lua
  plugins/exporter.koplugin/template/note.tpl
  plugins/exporter.koplugin/template/slt2.lua
  spec/unit/exporter_plugin_main_spec.lua
Labels: Plugin, chore

#9075 Fix docs after Exporter plugin refactor
  doc/config.ld
Labels: chore

#9078 [doc] Update busted version mentioned in docs
  doc/Unit_tests.md
Labels: documentation

#9079 [i18n] Enable Latvian translation
  frontend/gettext.lua
  frontend/ui/language.lua
Labels: i18n

#9082 [i18n] Enable more languages
  frontend/ui/language.lua
Labels: i18n

#9086 fix: attempt to call local start_time (number)
  plugins/calibre.koplugin/metadata.lua
Labels: bug, Plugin

#9098 PocketBook: Don't break synthetic power input events on suspend
  frontend/device/input.lua
Labels: PocketBook

#9107 FilemanagerShortcuts: fix crash on adding the first shortcut
  frontend/apps/filemanager/filemanagershortcuts.lua
Labels: bug

#9121 Fix reMarkable crash bug v2022.05: event overwrite with new time module
  frontend/device/remarkable/device.lua
Labels: bug, reMarkable

#9123 Page turn animations: add to dispatcher
  frontend/apps/reader/modules/readerview.lua
  frontend/dispatcher.lua
  frontend/ui/elements/page_turns.lua
Labels: Kindle

#9113 [plugin, statistics] simplify ReaderProgress for better translations
  plugins/statistics.koplugin/readerprogress.lua
Labels: i18n

#9130 Fix export file disappearance in some devices
  plugins/exporter.koplugin/base.lua
Labels: Plugin

#9124 AutoSuspend: Don't send LeaveStandby events from a zombie plugin instance
  frontend/apps/reader/modules/readerdictionary.lua
  frontend/device/wakeupmgr.lua
  frontend/ui/uimanager.lua
  frontend/ui/widget/confirmbox.lua
  frontend/ui/widget/infomessage.lua
  plugins/autosuspend.koplugin/main.lua
Labels: bug

#9076 Markdown export
  plugins/exporter.koplugin/base.lua
  plugins/exporter.koplugin/main.lua
  plugins/exporter.koplugin/target/joplin.lua
  plugins/exporter.koplugin/target/markdown.lua
  plugins/exporter.koplugin/template/md.lua
Labels: Plugin

#9145 DateTimeWidget: don't make ":" and "/" translatable
  frontend/apps/reader/modules/readerhighlight.lua
  frontend/ui/widget/datetimewidget.lua
Labels: i18n
