Repository koreader/koreader, pull requests merged in 2022-10, with the labels that each got.

#9528 vocabbuilder.koplugin: support undo word study
  plugins/vocabbuilder.koplugin/db.lua
  plugins/vocabbuilder.koplugin/main.lua
Labels: Plugin

#9580 ConfigDialog: fix bug in DoubleSpinWidget default values
  frontend/apps/reader/modules/readerdevicestatus.lua
  frontend/apps/reader/modules/readertypography.lua
  frontend/ui/widget/configdialog.lua
  frontend/ui/widget/doublespinwidget.lua
  plugins/statistics.koplugin/main.lua
Labels: bug

#9496 Cloud storage: add Dropbox short-lived tokens
  frontend/apps/cloudstorage/cloudstorage.lua
  frontend/apps/cloudstorage/dropbox.lua
  frontend/apps/cloudstorage/dropboxapi.lua
Labels: Plugin

#9619 ReaderStatus: save status summary
  frontend/apps/reader/modules/readerstatus.lua
Labels: bug

#9605 vocabbuilder.koplugin: supports review in reverse order
  plugins/vocabbuilder.koplugin/db.lua
  plugins/vocabbuilder.koplugin/main.lua
Labels: Plugin

#9662 ConfigDialog: fix bug with default values
  frontend/ui/widget/configdialog.lua
Labels: bug

#9666 ConfigDialog: fix bug with default values 2
  frontend/ui/widget/configdialog.lua
Labels: bug

#9675 AutoDim: close trapper widget explicitly
  plugins/autodim.koplugin/main.lua
Labels: bug, Plugin

#9680 ScrollableContainer: fix 'argc'
  frontend/ui/widget/checkbutton.lua
  frontend/ui/widget/container/scrollablecontainer.lua
  frontend/ui/widget/keyboardlayoutdialog.lua
  frontend/ui/widget/radiobutton.lua
Labels: bug

#9672 Keyvaluepage: better alignment
  frontend/ui/widget/keyvaluepage.lua
Labels: UX

#9194 exporter.koplugin: send the right mimetype when sharing text.
  plugins/exporter.koplugin/base.lua
  plugins/exporter.koplugin/target/html.lua
  plugins/exporter.koplugin/target/json.lua
  plugins/exporter.koplugin/target/markdown.lua
  plugins/exporter.koplugin/target/text.lua
Labels: Plugin

#9681 Re-Do: New Feature, Stream from Page
  plugins/opds.koplugin/opdsbrowser.lua
Labels: Plugin

#9703 OPDSbrowser refactoring
  plugins/opds.koplugin/main.lua
  plugins/opds.koplugin/opdsbrowser.lua
  plugins/opds.koplugin/opdsparser.lua
  spec/unit/opds_spec.lua
Labels: Plugin, OPDS

#9718 OPDSbrowser: fix uninitialized calibre
  plugins/opds.koplugin/opdsbrowser.lua
Labels: bug, Plugin, OPDS

#9720 TextViewer: allow close on any multiswipe
  frontend/ui/widget/textviewer.lua
Labels: UX
