Repository koreader/koreader, pull requests merged in 2023-10, with the labels that each got.

#10945 10892 hash-based metadata storage
  datastorage.lua
  frontend/docsettings.lua
  frontend/document/document.lua
  frontend/ui/elements/common_settings_menu_table.lua
  frontend/util.lua
Labels: enhancement

#10974 [doc] Building targets: remove mentions of Ubuntu Touch
  doc/Building_targets.md
Labels: documentation

#10987 Add new PocketBook devices PB-Basic Lux 4 (PB618)
  frontend/device/pocketbook/device.lua
Labels: PocketBook

#11008 Vocabbuilder: fix docless title
  plugins/vocabbuilder.koplugin/main.lua
Labels: bug, Plugin

#11000 README: update user guide link
  README.md
Labels: documentation
