Repository koreader/koreader, pull requests merged in 2023-03, with the labels that each got.

#10172 [i18n] Improve clarity for translators
  plugins/calibre.koplugin/search.lua
Labels: i18n

#10195 vocabbuilder.koplugin: fix reset word progress bug
  plugins/vocabbuilder.koplugin/main.lua
Labels: bug, Plugin

#10205 Readerzooming: fix use of default settings
  frontend/apps/reader/modules/readerpaging.lua
  frontend/apps/reader/modules/readerzooming.lua
Labels: bug

#10247 Style tweaks: update profiles on unregistering in Dispatcher
  frontend/apps/reader/modules/readerstyletweak.lua
Labels: bug, Plugin

#10244 History: fix book info buttons disable
  frontend/apps/filemanager/filemanagerhistory.lua
  frontend/apps/filemanager/filemanagerutil.lua
  frontend/readhistory.lua
Labels: bug

#10257 History: fix clear missing
  frontend/readhistory.lua
Labels: bug

#10260 Fix: Updated legacy directory, which crashed the program
  plugins/exporter.koplugin/clip.lua
Labels: bug, Plugin

#10271 Dispatcher: translate QuickMenu title
  frontend/dispatcher.lua
Labels: bug, i18n
