Repository koreader/koreader, pull requests merged in 2024-04, with the labels that each got.

#11614 [i18n] Font UI fallbacks: insert replacement characters with template for Weblate compatibility
  frontend/ui/elements/font_ui_fallbacks.lua
Labels: i18n

#11601 Fix PocketBook losing net access (#10183)
  frontend/device/pocketbook/device.lua
  frontend/ui/network/manager.lua
Labels: PocketBook

#11643 GetText: fix crash if a value is used as unique value and as singular/plural
  frontend/gettext.lua
Labels: bug, i18n

#11648 [i18n] GetText: fix fuzzy detection for certain strings
  frontend/gettext.lua
Labels: i18n

#11661 doc: remove ragel from the build requirements
  doc/Building.md
Labels: documentation

#11690 hidden flows and custom toc removed from non-touch devices
  frontend/apps/reader/modules/readerhandmade.lua
Labels: NT

#11695 Add PocketBook Era Color (PB700K3)
  frontend/device/pocketbook/device.lua
Labels: PocketBook

#11696 Kindle Scribe: fix gyro device detection (again)
  frontend/device/kindle/device.lua
Labels: Kindle

#11721 pocketbook: simplify device model detection
  frontend/device/pocketbook/device.lua
Labels: PocketBook
