Repository koreader/koreader, pull requests merged in 2024-01, with the labels that each got.

#11321 Fix "Move current book to archive"
  plugins/movetoarchive.koplugin/main.lua
Labels: bug, Plugin

#11330 i18n: Don't use Lua unicode escapes
  frontend/ui/elements/screen_notification_menu_table.lua
Labels: i18n

#11107 Exporter: memos, replace space with underscore for # tag creation
  plugins/exporter.koplugin/target/memos.lua
Labels: Plugin

#11300 FileChooser: fixes
  frontend/ui/widget/filechooser.lua
Labels: bug

#11277 Kindle Oasis 1,2,3, Scribe: fix startup orientation
  frontend/device/kindle/device.lua
Labels: Kindle

#11343 Fix of messed up Slovak keyboard layout
  frontend/ui/data/keyboardlayouts/keypopup/sk_popup.lua
  frontend/ui/data/keyboardlayouts/sk_keyboard.lua
Labels: bug

#11346 Fix Classic mode items per page setting
  frontend/apps/filemanager/filemanagermenu.lua
Labels: bug

#11356 CoverBrowser: fix cover cache check
  plugins/coverbrowser.koplugin/bookinfomanager.lua
Labels: bug

#11365 Virtual keyboard: Scandinavian layouts (Norwegian, Swedish & Danish)
  frontend/ui/data/keyboardlayouts/da_keyboard.lua
  frontend/ui/data/keyboardlayouts/no_keyboard.lua
  frontend/ui/data/keyboardlayouts/sv_keyboard.lua
  frontend/ui/language.lua
  frontend/ui/widget/virtualkeyboard.lua
Labels: i18n

#11360 CoverBrowser: doc_settings cache improvement
  frontend/apps/filemanager/filemanagerutil.lua
  plugins/coverbrowser.koplugin/covermenu.lua
  plugins/coverbrowser.koplugin/main.lua
Labels: Plugin

#11396 Text editor: refresh path on saving file
  plugins/texteditor.koplugin/main.lua
Labels: Plugin
