Repository koreader/koreader, pull requests merged in 2024-03, with the labels that each got.

#11513 Upper menu: fix generating the menu
  frontend/apps/filemanager/filemanagermenu.lua
  frontend/apps/reader/modules/readermenu.lua
  frontend/ui/widget/touchmenu.lua
Labels: bug

#11532 Wallabag: properly deal with mimetype actually being content-type
  plugins/wallabag.koplugin/main.lua
Labels: Plugin

#11569 [fix] ReaderLink: fix copy link
  frontend/apps/reader/modules/readerlink.lua
Labels: bug

#11577 Add en-GB and Romanian translation to UI
  frontend/ui/language.lua
Labels: i18n
