Repository koreader/koreader, pull requests merged in 2025-04, with the labels that each got.

#13511 Key press handlers to show upper menu
  frontend/apps/filemanager/filemanagermenu.lua
  frontend/apps/reader/modules/readermenu.lua
  plugins/hotkeys.koplugin/main.lua
Labels: NT

#13484 [plugin] calibre: fix a nil concatenation typo
  plugins/calibre.koplugin/search.lua
Labels: Plugin

#13541 [plugin] HttpInspector: fix crash when starting server
  frontend/ui/message/simpletcpserver.lua
Labels: bug, Plugin

#13561 Statistics: do not read settings for pic documents
  plugins/statistics.koplugin/main.lua
Labels: bug, Plugin

#13592 Statistics: revert erroneous nextTick in onReaderReady()
  plugins/statistics.koplugin/main.lua
Labels: bug, Plugin

#13596 Debian: misc changes
  frontend/device/devicelistener.lua
  platform/linux/do_debian_package.sh
  plugins/terminal.koplugin/profile
Labels: Desktop

#13603 add kindle basic 5 hall file
  frontend/device/kindle/device.lua
Labels: Kindle

#13615 add hall file for PW6
  frontend/device/kindle/device.lua
Labels: Kindle

#13607 Fix Location Stack Issues
  frontend/apps/reader/modules/readerpaging.lua
Labels: bug

#13634 [i18n] Change Korean language name
  frontend/ui/language.lua
Labels: i18n

#13637 Issue template: ask for firmware version
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: documentation
